export interface GalleryItem {
  id: string
  type: "image" | "video"
  title: string
  description: string
  url: string
  thumbnailUrl?: string
  category: string
  country: string
  tags: string[]
  alt: string
  photographer?: string
  date: string
}

export const galleryItems: GalleryItem[] = [
  {
    id: "1",
    type: "image",
    title: "Masai Mara Great Migration",
    description: "Thousands of wildebeest crossing the Mara River during the annual Great Migration. One of nature's most spectacular events.",
    url: "/4-Days-Masai-Mara-Wildebeest-safari.jpg",
    category: "Wildlife",
    country: "Kenya",
    tags: ["Great Migration", "Wildebeest", "Masai Mara", "Wildlife", "River Crossing"],
    alt: "Wildebeest crossing the Mara River during the Great Migration in Masai Mara, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2024-08-15",
  },
  {
    id: "2",
    type: "image",
    title: "Mountain Gorilla Family",
    description: "A silverback mountain gorilla with his family in Bwindi Impenetrable Forest. An intimate moment with these endangered primates.",
    url: "/06-08-2013-PNVi-Gorilles-Brent-Striton-09275-1400x928.jpg",
    category: "Primates",
    country: "Uganda",
    tags: ["Mountain Gorillas", "Bwindi", "Silverback", "Primates", "Conservation"],
    alt: "Silverback mountain gorilla with family in Bwindi Impenetrable Forest, Uganda",
    photographer: "JaeTravel Expeditions",
    date: "2024-07-22",
  },
  {
    id: "3",
    type: "video",
    title: "Serengeti Sunset Safari",
    description: "Experience the golden hour in Serengeti National Park as elephants and giraffes roam the endless plains.",
    url: "/videos/serengeti-sunset.mp4",
    thumbnailUrl: "/360_F_571293913_j01M0oaWJPsCkwPmb0TBrAPfzIGH8Ope.jpg",
    category: "Landscapes",
    country: "Tanzania",
    tags: ["Serengeti", "Sunset", "Elephants", "Giraffes", "Golden Hour"],
    alt: "Sunset safari in Serengeti National Park with elephants and giraffes",
    photographer: "JaeTravel Expeditions",
    date: "2024-09-10",
  },
  {
    id: "4",
    type: "image",
    title: "Amboseli Elephants with Kilimanjaro",
    description: "Majestic elephants walking across Amboseli with Mount Kilimanjaro's snow-capped peak in the background.",
    url: "/Amboseli-National-Park.jpg",
    category: "Wildlife",
    country: "Kenya",
    tags: ["Amboseli", "Elephants", "Mount Kilimanjaro", "Landscape", "Wildlife"],
    alt: "Elephants in Amboseli National Park with Mount Kilimanjaro in the background, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2024-06-18",
  },
  {
    id: "5",
    type: "image",
    title: "Ngorongoro Crater Panorama",
    description: "Breathtaking aerial view of Ngorongoro Crater, the world's largest intact volcanic caldera teeming with wildlife.",
    url: "/panoramic-view-of-ngorongoro-crater-john-bryant.jpg",
    category: "Landscapes",
    country: "Tanzania",
    tags: ["Ngorongoro", "Crater", "Caldera", "Aerial View", "Landscape"],
    alt: "Aerial panoramic view of Ngorongoro Crater, Tanzania",
    photographer: "JaeTravel Expeditions",
    date: "2024-08-05",
  },
  {
    id: "6",
    type: "video",
    title: "Rwanda Gorilla Trekking Experience",
    description: "Follow our guests on an unforgettable gorilla trekking adventure in Volcanoes National Park, Rwanda.",
    url: "/videos/rwanda-gorilla-trekking.mp4",
    thumbnailUrl: "/gorilla-trekking-difficulty.jpg",
    category: "Primates",
    country: "Rwanda",
    tags: ["Gorilla Trekking", "Rwanda", "Volcanoes National Park", "Adventure", "Primates"],
    alt: "Gorilla trekking experience in Volcanoes National Park, Rwanda",
    photographer: "JaeTravel Expeditions",
    date: "2024-07-30",
  },
  {
    id: "7",
    type: "image",
    title: "Maasai Cultural Dance",
    description: "Traditional Maasai warriors performing the iconic jumping dance during a cultural visit in Kenya.",
    url: "/Masai-Dance-1024x819.jpeg",
    category: "Culture",
    country: "Kenya",
    tags: ["Maasai", "Culture", "Traditional Dance", "Warriors", "Kenya"],
    alt: "Maasai warriors performing traditional jumping dance in Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2024-05-12",
  },
  {
    id: "8",
    type: "image",
    title: "Lake Nakuru Flamingos",
    description: "Thousands of pink flamingos creating a stunning spectacle on the shores of Lake Nakuru.",
    url: "/download.jpg",
    category: "Birds",
    country: "Kenya",
    tags: ["Flamingos", "Lake Nakuru", "Birds", "Pink", "Wildlife"],
    alt: "Thousands of pink flamingos on Lake Nakuru, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2024-04-20",
  },
  {
    id: "9",
    type: "video",
    title: "Accessible Safari Experience",
    description: "See how our wheelchair-adapted vehicles make safari adventures accessible for everyone.",
    url: "/videos/WhatsApp Video 2025-10-14 at 5.15.38 PM.mp4",
    thumbnailUrl: "/WhatsApp Image 2025-10-14 at 5.16.09 PM.jpeg",
    category: "Accessible Travel",
    country: "Kenya",
    tags: ["Accessible Safari", "Wheelchair", "Disability Travel", "Inclusive", "Adapted Vehicles"],
    alt: "Wheelchair-adapted safari vehicle for accessible travel in Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2024-09-01",
  },
  {
    id: "10",
    type: "image",
    title: "Zanzibar Beach Paradise",
    description: "Crystal-clear turquoise waters and white sand beaches of Zanzibar, the perfect post-safari relaxation.",
    url: "/view-from-the-room.jpg",
    category: "Beaches",
    country: "Tanzania",
    tags: ["Zanzibar", "Beach", "Paradise", "Turquoise Water", "Relaxation"],
    alt: "White sand beach with turquoise water in Zanzibar, Tanzania",
    photographer: "JaeTravel Expeditions",
    date: "2024-08-28",
  },
  {
    id: "11",
    type: "image",
    title: "Chimpanzee in Kibale Forest",
    description: "A curious chimpanzee in Kibale National Park, Uganda's primate capital with 13 primate species.",
    url: "/Chimpanzee-Tracking-in-Kibale-National-Park.jpg",
    category: "Primates",
    country: "Uganda",
    tags: ["Chimpanzee", "Kibale", "Primates", "Uganda", "Forest"],
    alt: "Chimpanzee in Kibale National Park, Uganda",
    photographer: "JaeTravel Expeditions",
    date: "2024-06-05",
  },
  {
    id: "12",
    type: "image",
    title: "Murchison Falls Power",
    description: "The mighty Nile River squeezing through a narrow gorge at Murchison Falls, creating a thunderous spectacle.",
    url: "/Murchison-Falls-750x450.jpg",
    category: "Landscapes",
    country: "Uganda",
    tags: ["Murchison Falls", "Waterfall", "Nile River", "Uganda", "Nature"],
    alt: "Murchison Falls waterfall on the Nile River, Uganda",
    photographer: "JaeTravel Expeditions",
    date: "2024-07-15",
  },
  {
    id: "13",
    type: "video",
    title: "Hot Air Balloon Safari",
    description: "Soar above the Masai Mara at sunrise in a hot air balloon for a bird's-eye view of the wildlife below.",
    url: "/videos/balloon-safari.mp4",
    thumbnailUrl: "/hot-air-balloon-safari-masai-mara.jpg",
    category: "Adventure",
    country: "Kenya",
    tags: ["Hot Air Balloon", "Masai Mara", "Sunrise", "Adventure", "Aerial View"],
    alt: "Hot air balloon safari over Masai Mara at sunrise, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2024-08-20",
  },
  {
    id: "14",
    type: "image",
    title: "Lake Kivu Serenity",
    description: "Peaceful sunset over Lake Kivu in Rwanda, one of Africa's Great Lakes surrounded by lush hills.",
    url: "/Lake-Kivu-2.jpg",
    category: "Landscapes",
    country: "Rwanda",
    tags: ["Lake Kivu", "Sunset", "Rwanda", "Peaceful", "Great Lakes"],
    alt: "Sunset over Lake Kivu, Rwanda",
    photographer: "JaeTravel Expeditions",
    date: "2024-05-28",
  },
  {
    id: "15",
    type: "image",
    title: "Leopard in Acacia Tree",
    description: "A leopard resting on an acacia tree branch in Serengeti, showcasing the big cat's incredible climbing ability.",
    url: "/c0408378-800px-wm.jpg",
    category: "Wildlife",
    country: "Tanzania",
    tags: ["Leopard", "Big Cats", "Serengeti", "Acacia Tree", "Wildlife"],
    alt: "Leopard resting on acacia tree in Serengeti National Park, Tanzania",
    photographer: "JaeTravel Expeditions",
    date: "2024-09-05",
  },
  {
    id: "16",
    type: "image",
    title: "Akagera National Park Lions",
    description: "A pride of lions in Akagera National Park, Rwanda's only savanna park where the Big Five have been reintroduced.",
    url: "/52522795fbaa409889dd4b50463fde85.jpg",
    category: "Wildlife",
    country: "Rwanda",
    tags: ["Lions", "Akagera", "Big Five", "Rwanda", "Pride"],
    alt: "Pride of lions in Akagera National Park, Rwanda",
    photographer: "JaeTravel Expeditions",
    date: "2024-06-30",
  },
  // New Accessible Vehicle Videos (IDs 17-25)
  {
    id: "17",
    type: "video",
    title: "Wheelchair Ramp Deployment in Masai Mara",
    description: "Watch our custom Land Cruiser deploy its hydraulic ramp for seamless wheelchair access during a Masai Mara game drive.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.12.11_426ad508.mp4",
    thumbnailUrl: "/masai-mara-wheelchair-height.jpg",
    category: "Accessible Travel",
    country: "Kenya",
    tags: ["Wheelchair Ramp", "Land Cruiser", "Masai Mara", "Accessible Safari", "Hydraulic Lift"],
    alt: "Wheelchair ramp deploying on adapted Land Cruiser in Masai Mara, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2025-09-05",
  },
  {
    id: "18",
    type: "video",
    title: "Secure Wheelchair Restraints on Safari Drive",
    description: "See how we secure wheelchairs with 4x4 floor restraints for safe, bumpy rides through the African bush.",
    url: "/videos/WhatsApp Video 2025-10-14 at 5.15.38 PM.mp4",
    thumbnailUrl: "/wheelchair-restraints-header-mobile.jpg",
    category: "Accessible Travel",
    country: "Kenya",
    tags: ["Wheelchair Restraints", "Safety Features", "Safari Vehicle", "Inclusive Travel", "Bush Drive"],
    alt: "Securing wheelchair in adapted safari vehicle with restraints, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2025-08-20",
  },
  {
    id: "19",
    type: "video",
    title: "Elevated Viewing Seats for All Guests",
    description: "Our adapted Prado vehicles feature adjustable seats so everyone gets prime wildlife viewing positions.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.12.12_c02d399c.mp4",
    thumbnailUrl: "/Extended-Safari-Vehicle-Seating-configuration-Seven-seater-web.jpg",
    category: "Accessible Travel",
    country: "Tanzania",
    tags: ["Elevated Seats", "Prado Vehicle", "Wildlife Viewing", "Wheelchair Accessible", "Serengeti"],
    alt: "Adjustable elevated seats in accessible Prado for safari viewing, Tanzania",
    photographer: "JaeTravel Expeditions",
    date: "2025-09-10",
  },
  {
    id: "20",
    type: "video",
    title: "Hydraulic Lift Operation Demo",
    description: "Step-by-step demo of our vehicle's hydraulic lift, making boarding effortless for wheelchair users.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.12.12_c02d399c.mp4",
    thumbnailUrl: "/Screenshot-2023-09-02-at-2.23.52-pm-e1693779777688.png",
    category: "Accessible Travel",
    country: "Kenya",
    tags: ["Hydraulic Lift", "Vehicle Demo", "Wheelchair Boarding", "Accessible Features", "East Africa"],
    alt: "Hydraulic lift demonstration on wheelchair-adapted safari vehicle, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2025-10-01",
  },
  {
    id: "21",
    type: "video",
    title: "Game Drive with Adapted 4x4 Vehicle",
    description: "Join a full game drive in our wheelchair-friendly 4x4, spotting lions and elephants from a secure, comfortable spot.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.13.22_5ebb1061.mp4",
    thumbnailUrl: "/cd.jpg",
    category: "Accessible Travel",
    country: "Uganda",
    tags: ["Game Drive", "4x4 Vehicle", "Wheelchair Friendly", "Big Five", "Queen Elizabeth Park"],
    alt: "Wheelchair-accessible 4x4 game drive spotting wildlife, Uganda",
    photographer: "JaeTravel Expeditions",
    date: "2025-08-15",
  },
  {
    id: "22",
    type: "video",
    title: "Body Belt Safety During Rough Terrain",
    description: "Safety first: Our body belts keep wheelchair passengers secure over rocky savanna terrain.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.13.33_036dbbff.mp4",
    thumbnailUrl: "/download.avif",
    category: "Accessible Travel",
    country: "Rwanda",
    tags: ["Body Belt", "Safety Gear", "Rough Terrain", "Disability Safari", "Akagera Park"],
    alt: "Body belt securing passenger in wheelchair on rough terrain safari, Rwanda",
    photographer: "JaeTravel Expeditions",
    date: "2025-09-20",
  },
  {
    id: "23",
    type: "video",
    title: "Wheelchair Storage in Vehicle Hold",
    description: "Efficient storage solutions keep your wheelchair protected while you enjoy the safari from elevated seats.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.13.40_d7d72a71.mp4",
    thumbnailUrl: "/australian-prado-250-boot-space-v0-2xofkpu2o7yd1.webp",
    category: "Accessible Travel",
    country: "Tanzania",
    tags: ["Wheelchair Storage", "Vehicle Hold", "Protected Transport", "Inclusive Safari", "Ngorongoro"],
    alt: "Secure wheelchair storage in adapted safari vehicle hold, Tanzania",
    photographer: "JaeTravel Expeditions",
    date: "2025-07-30",
  },
  {
    id: "24",
    type: "video",
    title: "Ramp-Assisted Wildlife Spotting",
    description: "Using the side ramp for quick access during prime wildlife spotting moments in the bush.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.12.11_f6e4140d.mp4",
    thumbnailUrl: "/WhatsApp Image 2025-10-14 at 21.13.22_84137fdf.jpg",
    category: "Accessible Travel",
    country: "Kenya",
    tags: ["Side Ramp", "Wildlife Spotting", "Quick Access", "Adapted Land Cruiser", "Amboseli"],
    alt: "Ramp-assisted access for wildlife spotting in Kenya safari vehicle",
    photographer: "JaeTravel Expeditions",
    date: "2025-10-05",
  },
  {
    id: "25",
    type: "video",
    title: "Full Vehicle Tour for Inclusive Travel",
    description: "360° tour of our fully adapted safari vehicle, from ramps to viewing platforms—built for everyone.",
    url: "/videos/WhatsApp Video 2025-10-14 at 21.12.12_c02d399c.mp4",
    thumbnailUrl: "/WhatsApp Image 2025-10-14 at 21.13.42_2a015ee0.jpg",
    category: "Accessible Travel",
    country: "Kenya",
    tags: ["Vehicle Tour", "Inclusive Design", "360 View", "Wheelchair Adapted", "Safari Features"],
    alt: "Complete tour of wheelchair-accessible safari vehicle interior and exterior, Kenya",
    photographer: "JaeTravel Expeditions",
    date: "2025-10-14",
  },
]

export const galleryCategories = [
  "All",
  "Wildlife",
  "Primates",
  "Landscapes",
  "Culture",
  "Birds",
  "Beaches",
  "Adventure",
  "Accessible Travel",
]

export const galleryCountries = ["All", "Kenya", "Tanzania", "Rwanda", "Uganda"]