export const products = [
  {
    id: "1",
    slug: "best-of-kenya-tanzania",
    name: "Best of Kenya & Tanzania - The Ultimate Migration Experience",
    heroImage: "/4-Days-Masai-Mara-Wildebeest-safari.jpg",
    description: "Embark on an epic 10-day safari odyssey across Kenya and Tanzania, where thundering herds of wildebeest and majestic lions await in the legendary Maasai Mara and Serengeti. Experience the greatest wildlife spectacle on earth.",
    details: "Feel the pulse of the wild on this comprehensive 10-day journey through East Africa's most iconic landscapes. Chase the awe-inspiring Great Migration across the Mara River, where crocodiles await their annual feast. Marvel at Ngorongoro Crater's wildlife haven - a natural amphitheater teeming with over 25,000 large animals. Connect authentically with Maasai warriors who share ancient traditions, and meet the Hadzabe, one of Africa's last remaining hunter-gatherer tribes. From golden savannas to starlit nights around campfires, this premium adventure blends luxury lodges with authentic cultural immersion. Each day brings new wonders: sunrise game drives when predators are most active, picnic lunches under acacia trees, and evenings reflecting on unforgettable sightings. Our carefully curated itinerary ensures you experience the essence of East Africa while supporting sustainable tourism initiatives.",
    highlights: [
      "Witness the dramatic Mara River crossings during the Great Migration (July-October)",
      "Spot all Big Five animals in their natural habitats with expert trackers",
      "Spend a full day exploring Ngorongoro Crater, a UNESCO World Heritage Site",
      "Immersive cultural visit with Maasai community including traditional dance and crafts",
      "Night game drive in a private conservancy to spot nocturnal wildlife",
      "Hot air balloon safari over the Serengeti with champagne breakfast (optional)",
      "Photography sessions with professional safari photography tips",
      "Stay in luxury tented camps with 360-degree views of the wilderness"
    ],
    itinerary: [
      "Day 1: Arrive at Jomo Kenyatta International Airport, Nairobi. VIP meet-and-greet service. Transfer to boutique hotel for orientation and welcome dinner featuring Kenyan cuisine.",
      "Day 2-3: Fly to Maasai Mara. Morning and afternoon game drives focusing on migration herds. Visit to Maasai village for cultural exchange. Sundowner drinks overlooking the plains.",
      "Day 4: Cross-border transfer to Serengeti via Isebania border. Afternoon game drive en route to luxury camp. Evening wildlife presentation by resident naturalist.",
      "Day 5-6: Full days in Serengeti with flexible game drives. Options include predator tracking, bird watching (over 500 species), and visiting remote regions few tourists see.",
      "Day 7: Descend into Ngorongoro Crater for full-day exploration with picnic lunch at Hippo Pool. Afternoon visit to Olduvai Gorge, 'Cradle of Mankind'.",
      "Day 8: Cultural immersion day with Hadzabe tribe learning bush skills and traditional hunting techniques (non-violent demonstration). Evening storytelling around campfire.",
      "Day 9: Return to Arusha via Lake Manyara (famous for tree-climbing lions). Farewell dinner at legendary Arusha Coffee Lodge.",
      "Day 10: Transfer to Kilimanjaro International Airport with packed lunch and safari memories to last a lifetime."
    ],
    price: 6500,
    currency: "USD",
    rating: 4.9,
    reviewCount: 45,
    duration: "10 Days / 9 Nights",
    difficulty: "Moderate (some early starts and bumpy roads)",
    groupSize: "Maximum 8 travelers for personalized experience",
    category: "Premium Classic Safari",
    included: [
      "All accommodation in luxury lodges and tented camps",
      "Three meals daily plus snacks and beverages (excluding premium alcohol)",
      "Professional English/French speaking driver-guide with 10+ years experience",
      "Private 4x4 Land Cruiser with pop-up roof, fridge, and charging ports",
      "All national park fees and conservation levies",
      "Internal flights Nairobi-Maasai Mara",
      "All cultural visit fees and community donations",
      "Complimentary binoculars and wildlife reference books",
      "Emergency medical evacuation coverage",
      "24/7 in-country support from our operations team"
    ],
    excluded: [
      "International flights to/from East Africa",
      "Comprehensive travel insurance (mandatory)",
      "Kenya and Tanzania visa fees (approx. $100 total)",
      "Optional hot air balloon safari ($550 per person)",
      "Premium alcoholic beverages and imported wines",
      "Personal purchases and gratuities (recommended $20-$30 per day)",
      "COVID-19 testing if required (we assist with arrangements)"
    ],
    ctaText: "Reserve Your Epic Migration Safari",
    keywords: [
      "Kenya Tanzania Combined Safari",
      "Great Migration Tour",
      "Maasai Mara Serengeti Experience",
      "Big Five Safari East Africa",
      "Luxury African Safari Package",
      "Cross-Border Safari Adventure",
      "Wildebeest Migration River Crossings",
      "Cultural Safari Kenya Tanzania"
    ],
    metaTitle: "Best of Kenya & Tanzania: 10-Day Luxury Migration Safari | Jae Travel Expeditions",
    metaDescription: "Experience Africa's greatest wildlife spectacle on our 10-day premium Kenya-Tanzania safari. Witness the Great Migration, track Big Five, and immerse in Maasai culture with expert guides. All-inclusive luxury package.",
    bestTime: "July to October for migration crossings; January to March for calving season",
    departureDates: "Weekly departures every Saturday",
    accommodation: "Luxury tented camps and 5-star lodges",
    ageRestriction: "Minimum age 12 years (family departures available)",
    sustainability: "Carbon-offset program, community tourism certified, plastic-free operations"
  },
  {
    id: "2",
    slug: "safari-simba",
    name: "Safari Simba: Amboseli & Tsavo Wilderness Expedition",
    heroImage: "/images.jpeg",
    description: "Roar into adventure with Safari Simba, a 7-day journey where Kenya's Amboseli and Tsavo National Parks unveil massive elephant herds grazing beneath Kilimanjaro's snow-capped peak and lions prowling through vast red-earth landscapes.",
    details: "This carefully crafted 7-day thrill ride immerses you in two of Kenya's most diverse ecosystems. Begin in Amboseli, where over 1,500 elephants roam freely against the breathtaking backdrop of Africa's highest peak - Mount Kilimanjaro. Photograph iconic scenes of elephants with Kilimanjaro's summit glowing in sunrise light. Then venture into Tsavo's untamed wilderness, divided into East and West sections totaling over 20,000 square kilometers. Here, the 'red elephants' of Tsavo (colored by iron-rich dust) mingle with prides of lions, elusive leopards, and massive herds of buffalo. Stay in eco-conscious lodges designed to blend with the environment, each offering unique perspectives on the wilderness. Your expert guide will share insights into predator-prey dynamics, conservation success stories, and geological wonders like Mzima Springs and Shetani Lava Flows. This safari balances intense wildlife viewing with relaxing moments to absorb Africa's majestic beauty.",
    highlights: [
      "Iconic Kilimanjaro views with elephant herds at sunrise in Amboseli",
      "Track the famous 'Man-eaters of Tsavo' descendants in Tsavo West",
      "Underground viewing hide at Mzima Springs to watch hippos underwater",
      "Visit Shetani Lava Flows with geological interpretation",
      "Night game drive in Tsavo's private conservancy",
      "Photography workshop focusing on landscape and wildlife composition",
      "Birdwatching for Tsavo's 500+ species including migratory birds",
      "Swimming pool relaxation with wilderness views at eco-lodges"
    ],
    itinerary: [
      "Day 1: Nairobi arrival. Briefing and overnight at Hemingways Nairobi with rooftop views of the city.",
      "Day 2: Scenic drive to Amboseli via Maasai countryside. Afternoon game drive focusing on elephants with Kilimanjaro backdrop. Sunset drinks at Observation Hill.",
      "Day 3: Full day in Amboseli with morning and afternoon game drives. Visit Maasai community project. Optional guided nature walk with armed ranger.",
      "Day 4: Transfer to Tsavo West via Chyulu Hills. Afternoon visit to Mzima Springs and volcanic formations. Evening presentation on Tsavo's famous lions.",
      "Day 5: Tsavo West exploration including Rhino Sanctuary, Ngulia Rhino Sanctuary, and possibly leopard sightings. Night game drive in private area.",
      "Day 6: Transfer to Tsavo East for 'red elephant' viewing and Aruba Dam waterhole observation. Afternoon game drive focusing on predators.",
      "Day 7: Final morning game drive before returning to Nairobi with picnic lunch en route. Day room available for evening departures."
    ],
    price: 4200,
    currency: "USD",
    rating: 4.7,
    reviewCount: 32,
    duration: "7 Days / 6 Nights",
    difficulty: "Easy to Moderate",
    groupSize: "Maximum 6 travelers for optimal vehicle window seats",
    category: "Classic Wildlife Safari",
    included: [
      "Eco-lodge accommodations with swimming pools",
      "All meals from dinner Day 1 to lunch Day 7",
      "Private 4x4 safari vehicle with pop-up roof and charging stations",
      "Professional driver-guide with 7+ years Tsavo experience",
      "All park fees and conservation charges",
      "Bottled water and soft drinks in vehicle",
      "Night game drive in Tsavo West conservancy",
      "Community visit fees and donations",
      "Emergency oxygen tank and first aid kit"
    ],
    excluded: [
      "International flights to Nairobi",
      "Travel insurance with medical evacuation",
      "Alcoholic beverages and premium wines",
      "Gratuities for guides and lodge staff",
      "Optional activities like bush walks ($65)",
      "Visa for Kenya (obtainable online)",
      "Personal shopping and souvenirs"
    ],
    ctaText: "Book Your Simba Adventure Today",
    keywords: [
      "Safari Simba Kenya",
      "Amboseli Kilimanjaro Safari",
      "Tsavo National Park Tour",
      "Elephant Safari Kenya",
      "Red Elephants Tsavo",
      "Kenya Wildlife Photography",
      "Family Safari Kenya",
      "Eco-Tourism Kenya"
    ],
    metaTitle: "Safari Simba: 7-Day Amboseli & Tsavo Wildlife Expedition | Jae Travel Expeditions",
    metaDescription: "Join our 7-day Safari Simba expedition featuring Amboseli's elephants with Kilimanjaro views and Tsavo's legendary lions. Eco-friendly lodges, expert guides, and unforgettable wildlife encounters.",
    bestTime: "Year-round; best wildlife viewing June-October & January-February",
    departureDates: "Twice monthly on 1st and 15th",
    accommodation: "Eco-lodges with solar power and water conservation",
    ageRestriction: "Minimum age 8 years",
    sustainability: "Supports Tsavo Trust anti-poaching, uses solar-powered lodges"
  },
  {
    id: "3",
    slug: "safari-twiga",
    name: "Safari Twiga: Nairobi's Wildlife & Conservation Experience",
    heroImage: "/images (1).jpeg",
    description: "Get up close with graceful Rothschild's giraffes and Kenya's vibrant wildlife on this 5-day conservation-focused journey through Nairobi's urban wilderness and sanctuary havens.",
    details: "Designed for families, first-time Africa visitors, and wildlife enthusiasts with limited time, Safari Twiga offers an immersive introduction to Kenya's conservation triumphs. Begin at the world-famous Giraffe Centre, where you can hand-feed endangered Rothschild's giraffes from a raised platform while learning about breeding programs that saved this subspecies from extinction. Continue to Nairobi National Park - the world's only wildlife capital where lions hunt with a skyline backdrop. Visit the David Sheldrick Wildlife Trust to witness the heroic work of elephant keepers fostering orphaned calves. Explore the Karen Blixen Museum and nearby animal sanctuaries. Each experience highlights successful conservation stories while providing intimate wildlife encounters. The pace allows for relaxation and cultural exploration in Nairobi's vibrant arts and dining scene. Perfect for adding a wildlife component to business trips or as an educational family holiday.",
    highlights: [
      "Kiss a giraffe at the Giraffe Centre's feeding platform",
      "Game drive in Nairobi National Park with city skyline photos",
      "Private fostering session at David Sheldrick elephant orphanage",
      "Visit to Nairobi Animal Orphanage for rescued wildlife",
      "Karen Blixen Museum tour (Out of Africa author)",
      "Kazuri Beads women's cooperative supporting single mothers",
      "Nairobi National Museum's extensive natural history collection",
      "Bomas of Kenya cultural show with traditional dances"
    ],
    itinerary: [
      "Day 1: Arrival at Nairobi. Transfer to Giraffe Manor or equivalent. Evening briefing and welcome cocktail overlooking giraffe paddock.",
      "Day 2: Morning at Giraffe Centre with keeper talk. Afternoon visit to David Sheldrick Wildlife Trust for 11am public feeding. Lunch at nearby restaurant.",
      "Day 3: Full day Nairobi National Park game drive with picnic lunch at Impala Observation Point. Afternoon visit to Animal Orphanage.",
      "Day 4: Cultural day - Karen Blixen Museum, Kazuri Beads, and optional lunch at The Talisman. Evening at Bomas of Kenya for traditional performances.",
      "Day 5: Visit Nairobi National Museum and Snake Park. Transfer to airport for departure with conservation pack including adoption certificate."
    ],
    price: 2800,
    currency: "USD",
    rating: 4.8,
    reviewCount: 25,
    duration: "5 Days / 4 Nights",
    difficulty: "Easy (all activities vehicle-based)",
    groupSize: "Maximum 10 travelers",
    category: "Family & Conservation Safari",
    included: [
      "Boutique hotel accommodations (Giraffe Manor if available)",
      "All meals as specified in itinerary",
      "Private vehicle with driver-guide",
      "All entrance fees and conservation donations",
      "Giraffe and elephant adoption certificates",
      "Bottled water throughout",
      "Cultural performance tickets",
      "24-hour concierge service in Nairobi"
    ],
    excluded: [
      "International flights",
      "Travel insurance",
      "Optional activities like helicopter tour",
      "Premium dining outside included meals",
      "Shopping and personal expenses",
      "Airport departure taxes"
    ],
    ctaText: "Reserve Your Giraffe Encounter",
    keywords: [
      "Safari Twiga Nairobi",
      "Giraffe Centre Experience",
      "Nairobi National Park Safari",
      "David Sheldrick Elephant Orphanage",
      "Family Safari Kenya",
      "Conservation Tourism Nairobi",
      "Short Safari Kenya",
      "Karen Blixen Tour"
    ],
    metaTitle: "Safari Twiga: 5-Day Nairobi Wildlife & Conservation Tour | Jae Travel Expeditions",
    metaDescription: "5-day family-friendly Nairobi safari featuring giraffe feeding, elephant orphanage visit, and Nairobi National Park game drives. Perfect introduction to Kenya's wildlife conservation.",
    bestTime: "Year-round; Nairobi's climate is consistently mild",
    departureDates: "Weekly every Monday and Friday",
    accommodation: "Boutique hotels with character",
    ageRestriction: "All ages welcome (special rates for children)",
    sustainability: "100% of conservation fees go directly to projects"
  },
  {
    id: "4",
    slug: "golden-monkey-gorilla-trekking-safari",
    name: "Golden Monkey & Gorilla Trekking: Rwanda's Primate Paradise",
    heroImage: "/gorilla-trekking-difficulty.jpg",
    description: "Trek into Rwanda's misty Volcanoes National Park to meet playful golden monkeys and gaze into the wise eyes of mountain gorillas during this 6-day primate-focused adventure in Africa's most biodiverse forests.",
    details: "This transformative 6-day journey takes you deep into the Virunga Mountains, home to approximately one-third of the world's remaining mountain gorillas. Your adventure begins in Kigali, Africa's cleanest and safest capital, before ascending into the volcanic highlands. Each trek is a unique experience - hiking through bamboo forests, giant lobelias, and montane vegetation with expert trackers who've spent years with specific gorilla families. The moment you lock eyes with a silverback gorilla is life-changing. Equally magical are the golden monkeys - endangered, energetic primates that leap through bamboo canopy in troupes of up to 80 individuals. Beyond trekking, you'll learn about Rwanda's remarkable conservation success story, visit community projects benefiting from tourism revenue, and reflect on the nation's history at the powerful Kigali Genocide Memorial. Accommodation in eco-lodges with fireplace-heated rooms complements days spent in cool mountain forests.",
    highlights: [
      "One-hour observation of mountain gorilla family in natural habitat",
      "Golden monkey trekking through bamboo forests",
      "Visit to Ellen DeGeneres Campus of the Dian Fossey Gorilla Fund",
      "Hike to Dian Fossey's grave and former research center",
      "Traditional Rwandan cooking class with local family",
      "Guided nature walk to spot 200+ bird species including Rwenzori turaco",
      "Cultural evening with Intore dancers and traditional music",
      "Scenic hike to volcanic lakes Burera and Ruhondo"
    ],
    itinerary: [
      "Day 1: Arrival Kigali. Genocide Memorial visit (profound but optional). Transfer to Volcanoes National Park area. Lodge orientation and trek briefing.",
      "Day 2: First gorilla trekking experience (2-6 hours depending on group location). Celebration dinner with fellow trekkers sharing experiences.",
      "Day 3: Golden monkey trek (easier, 1-3 hours). Afternoon visit to Iby'Iwacu Cultural Village or community projects.",
      "Day 4: Optional second gorilla trek (additional permit required) or Dian Fossey hike. Evening Rwandan cooking experience.",
      "Day 5: Return to Kigali via twin lakes with canoe ride. Final shopping at Caplaki Craft Village. Farewell dinner at renowned restaurant.",
      "Day 6: Kigali city tour including Kimironko Market and art galleries. Transfer to airport for departure."
    ],
    price: 5200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 18,
    duration: "6 Days / 5 Nights",
    difficulty: "Moderate to Challenging (altitude 2,500-3,000m, uneven terrain)",
    groupSize: "Maximum 6 travelers for personalized trekking",
    category: "Primate & Trekking Adventure",
    included: [
      "One gorilla trekking permit ($1,500 value)",
      "One golden monkey trekking permit ($100 value)",
      "Eco-lodge accommodations with fireplace heating",
      "All meals from dinner Day 1 to breakfast Day 6",
      "Professional English/French speaking guide and trackers",
      "4x4 transfers throughout itinerary",
      "Porter hire for trekking (one per person)",
      "All conservation fees and community contributions",
      "Complimentary trekking pole and waterproof backpack"
    ],
    excluded: [
      "International flights to Kigali",
      "Rwanda visa ($50, obtainable on arrival for most nationals)",
      "Optional second gorilla permit ($1,500)",
      "Travel insurance including helicopter evacuation",
      "Alcoholic beverages beyond house selections",
      "Personal trekking gear (rentals available)",
      "Tips for guides, trackers, and porters"
    ],
    ctaText: "Secure Your Gorilla Trekking Permit",
    keywords: [
      "Rwanda Gorilla Trekking",
      "Volcanoes National Park",
      "Golden Monkey Trekking Rwanda",
      "Mountain Gorilla Safari",
      "Dian Fossey Tour Rwanda",
      "Primate Safari Africa",
      "Rwanda Eco-Tourism",
      "Virunga Mountains Trek"
    ],
    metaTitle: "Rwanda Gorilla & Golden Monkey Trekking: 6-Day Primate Safari | Jae Travel Expeditions",
    metaDescription: "Trek to see mountain gorillas and golden monkeys in Rwanda's Volcanoes National Park. Includes permits, eco-lodges, expert guides. Life-changing primate encounters.",
    bestTime: "June-September and December-February (dry seasons for easier trekking)",
    departureDates: "Monthly on 5th and 20th (permits limited)",
    accommodation: "Eco-lodges with volcanic views and sustainability certifications",
    ageRestriction: "Minimum 15 years for gorilla trekking",
    sustainability: "100% of permit fees support conservation and local communities"
  },
  {
    id: "5",
    slug: "luxury-roof-top-camping",
    name: "Luxury Roof-Top Camping: Under African Stars",
    heroImage: "/safari-vehicle-extended-roof-for-photography.jpg",
    description: "Sleep under a blanket of stars in Kenya's wilderness, where innovative luxury roof-top tents blend adventure with indulgence, gourmet cuisine, and exclusive wildlife access in private conservancies.",
    details: "This 4-day glamping experience redefines traditional camping with state-of-the-art roof-top tents mounted on customized 4x4 vehicles. Each evening, your guide transforms the vehicle into a luxurious bedroom with memory foam mattresses, high-quality linen, mosquito nets, and private balcony overlooking the wilderness. As the sun sets, gather around the campfire for sundowner drinks while your private chef prepares a three-course dinner using fresh, local ingredients. Wake to coffee delivered to your tent as dawn breaks over the savanna. The mobility of roof-top camping allows access to remote areas where traditional lodges don't exist, increasing wildlife sightings. Experience the magic of hearing lions roar nearby while safely elevated above ground level. Ideal for couples seeking romance, photographers wanting unique perspectives, or adventurers craving authenticity without sacrificing comfort. Locations vary seasonally between Amboseli, Maasai Mara, and Laikipia plateau.",
    highlights: [
      "Sleep in luxury roof-top tents with 360-degree wilderness views",
      "Private chef preparing gourmet meals over campfire",
      "Exclusive access to wildlife-rich private conservancies",
      "Night sky safari with astronomer guide and telescope",
      "Mobile camping allowing following wildlife migration patterns",
      "Bush breakfast setup in scenic locations",
      "Guided bush walks with armed ranger for close encounters",
      "Solar-powered charging stations and Wi-Fi hotspot"
    ],
    itinerary: [
      "Day 1: Nairobi pick-up. Scenic drive to conservancy. Camp setup lesson. Evening game drive followed by welcome champagne dinner under stars.",
      "Day 2: Sunrise game drive with bush breakfast. Afternoon siesta in camp. Evening walking safari and night drive with spotlights.",
      "Day 3: Full day exploration moving camp to new location based on wildlife movements. Picnic lunch at scenic viewpoint. Sundowners at special sunset spot.",
      "Day 4: Final morning game drive with farewell brunch. Return to Nairobi with drop-off at airport or hotel by 4pm."
    ],
    price: 3500,
    currency: "USD",
    rating: 4.6,
    reviewCount: 22,
    duration: "4 Days / 3 Nights",
    difficulty: "Easy (all camp setup handled by staff)",
    groupSize: "Maximum 4 travelers (2 vehicles)",
    category: "Luxury Glamping Adventure",
    included: [
      "Luxury roof-top tent accommodations with bedding",
      "All meals - gourmet camp cuisine with paired South African wines",
      "Private 4x4 vehicle with guide and spotter",
      "Private conservancy fees (no crowds)",
      "All camping equipment and hot bush showers",
      "Chef and camp staff",
      "Bush walks with armed ranger",
      "Night game drives with specialized equipment",
      "Star-gazing session with laser pointer"
    ],
    excluded: [
      "International flights",
      "Travel insurance",
      "Premium champagne and spirits (standard included)",
      "Personal camping gear (provided)",
      "Gratuities for camp team",
      "Nairobi accommodation before/after"
    ],
    ctaText: "Elevate Your Safari Experience",
    keywords: [
      "Luxury Roof-Top Camping Kenya",
      "Glamping Safari Africa",
      "Mobile Tented Safari",
      "Private Conservancy Kenya",
      "Romantic Safari Kenya",
      "Photography Safari Kenya",
      "Exclusive Camping Experience",
      "Star-Gazing Safari"
    ],
    metaTitle: "Luxury Roof-Top Camping Safari: 4-Day Glamping Adventure | Jae Travel Expeditions",
    metaDescription: "Sleep in luxury roof-top tents under African stars. Gourmet meals, private conservancy access, and exclusive wildlife viewing. Ultimate glamping experience for couples and adventurers.",
    bestTime: "Year-round; dry seasons preferable (June-October, January-February)",
    departureDates: "Weekly on Mondays and Thursdays",
    accommodation: "Custom roof-top tents on 4x4 vehicles",
    ageRestriction: "Minimum 12 years (younger by arrangement)",
    sustainability: "Leave-no-trace principles, solar power, support local communities"
  },
  {
    id: "6",
    slug: "6-sustainable-travel-tips",
    name: "6 Sustainable Travel Tips: Your Guide to Responsible East African Adventure",
    heroImage: "/amboseli-elephants-00007.jpg",
    description: "Transform your East African adventure with our comprehensive guide featuring six essential eco-conscious strategies to travel responsibly, support local communities, and leave a positive conservation legacy.",
    details: "This isn't just a list - it's a philosophy for transformative travel. We've distilled decades of sustainable tourism experience into six actionable principles that benefit both traveler and host. Learn how to identify genuinely eco-friendly accommodations using our certification checklist. Discover which community tourism initiatives create meaningful economic impact versus 'poverty tourism.' Get insider tips on reducing your environmental footprint while maximizing cultural connections. We provide specific recommendations for ethical wildlife interactions, from gorilla trekking etiquette to responsible dolphin encounters. Learn how your spending choices can support women's cooperatives, youth education, and conservation research. Each tip includes practical examples, recommended operators, and common pitfalls to avoid. Whether you're a first-time visitor or a seasoned Africa traveler, this guide will deepen your experience while ensuring your tourism dollars create lasting positive change.",
    highlights: [
      "Certification guide: How to identify truly sustainable lodges vs 'greenwashing'",
      "Community tourism blueprint: Supporting projects that empower rather than exploit",
      "Plastic-free travel toolkit: From water purification to shopping alternatives",
      "Wildlife interaction ethics: Dos and don'ts for photography and encounters",
      "Carbon offsetting demystified: Effective programs vs token gestures",
      "Cultural exchange guidelines: Respectful engagement with local communities",
      "Packing for purpose: Items to bring that support local schools/clinics",
      "Digital resources: Apps and platforms for responsible travelers"
    ],
    itinerary: [
      "Principle 1: Choose Accommodations Wisely - Eco-rating system explained, recommended certified properties in East Africa, questions to ask before booking",
      "Principle 2: Support Authentic Community Initiatives - Identifying community-owned vs externally managed projects, recommended cultural experiences, fair payment guidelines",
      "Principle 3: Minimize Environmental Impact - Water conservation tips, waste reduction strategies, transportation choices, recommended eco-products for safari",
      "Principle 4: Respect Wildlife Responsibly - Safe distance guidelines, photography ethics, choosing ethical animal encounters, reporting concerns",
      "Principle 5: Travel Carbon-Consciously - Effective offset programs, low-carbon transportation options, itinerary planning for reduced footprint",
      "Principle 6: Engage in Regenerative Tourism - Skills sharing opportunities, appropriate donations, long-term relationship building, post-trip follow-up"
    ],
    price: 0,
    currency: "USD",
    rating: 4.5,
    reviewCount: 10,
    duration: "N/A (Digital Resource)",
    difficulty: "N/A",
    groupSize: "N/A",
    category: "Educational Travel Resource",
    included: [
      "Complete 25-page sustainable travel guide PDF",
      "Interactive East Africa sustainability map",
      "Directory of certified eco-lodges and camps",
      "Community project recommendations with contact details",
      "Packing checklist for responsible travel",
      "Cultural etiquette guide for 6 East African cultures",
      "Monthly sustainability newsletter subscription",
      "Access to responsible traveler community forum"
    ],
    excluded: [
      "Physical shipping (digital product only)",
      "Personal consultation (available as add-on)",
      "Accommodation or tour bookings"
    ],
    ctaText: "Download Your Free Guide Now",
    keywords: [
      "Sustainable Travel East Africa",
      "Eco-Friendly Safari Tips",
      "Responsible Tourism Guide",
      "Ethical Wildlife Tourism",
      "Community-Based Tourism",
      "Carbon Neutral Travel",
      "Eco-Conscious Packing",
      "Regenerative Travel Africa"
    ],
    metaTitle: "6 Sustainable Travel Tips for East Africa: Free Responsible Tourism Guide | Jae Travel Expeditions",
    metaDescription: "Download our free comprehensive guide to sustainable travel in East Africa. Learn eco-friendly practices, ethical wildlife viewing, and how to support local communities effectively.",
    bestTime: "N/A (Year-round resource)",
    departureDates: "Instant digital download",
    accommodation: "N/A",
    ageRestriction: "N/A",
    sustainability: "Digital product eliminates paper waste, supports our conservation education program"
  },
  {
    id: "7",
    slug: "toyota-prado",
    name: "Toyota Prado Safari Rental: Freedom to Explore East Africa",
    heroImage: "/WhatsApp Image 2025-10-14 at 21.13.25_75828e63.jpg",
    description: "Conquer East Africa's most rugged terrains with a fully-equipped Toyota Land Cruiser Prado - your independent adventure vehicle for epic self-drive safaris across Kenya and Tanzania's wilderness areas.",
    details: "Experience ultimate safari freedom with our premium Toyota Prado rentals, specifically modified for African conditions. Each vehicle comes equipped with: pop-up roof for 360-degree game viewing, heavy-duty suspension for rough tracks, dual battery system with inverter, GPS with pre-loaded safari routes, comprehensive recovery gear, fridge/freezer, and camping equipment packages. We provide detailed route planning, park fee assistance, and 24/7 roadside support. Whether you're a family wanting flexibility, photographers needing to wait for perfect light, or adventurers craving spontaneous exploration, our Prado fleet offers reliability and capability. Choose from flexible itineraries including the Northern Circuit (Amboseli-Samburu), Southern Circuit (Masai Mara-Serengeti), or Coastal Route (Mombasa-Tsavo). Includes comprehensive insurance, unlimited mileage, and pre-departure vehicle orientation with experienced safari driver training.",
    highlights: [
      "Toyota Land Cruiser Prado TX/L or VX models (2018-2022)",
      "Full safari conversion with pop-up roof and custom storage",
      "GPS with Tracks4Africa mapping and offline navigation",
      "Comprehensive recovery kit: sand tracks, compressor, tow ropes",
      "Dual battery system with 2000W inverter for camera charging",
      "Fully-equipped camping package available (tents, sleeping bags, kitchen)",
      "Satellite phone rental for remote area communication",
      "Child seats and additional accessories available"
    ],
    itinerary: [
      "Day 1: Vehicle collection in Nairobi or Arusha with comprehensive orientation. Route planning session with our experts. Optional first night at our recommended lodge.",
      "Day 2-6: Self-drive adventure following your chosen route. Daily check-in calls from our support team. Flexibility to change plans based on wildlife reports.",
      "Day 7: Return vehicle to designated drop-off point. Debrief and sharing of wildlife sightings for our community map."
    ],
    price: 150,
    currency: "USD",
    rating: 4.4,
    reviewCount: 15,
    duration: "Flexible (3-day minimum, 21-day maximum)",
    difficulty: "Moderate (requires confident off-road driving)",
    groupSize: "Vehicle accommodates up to 5 adults comfortably",
    category: "Self-Drive Safari Rental",
    included: [
      "Toyota Prado 4x4 rental with comprehensive insurance",
      "Unlimited mileage within Kenya/Tanzania",
      "Full tank of diesel at collection",
      "GPS with pre-loaded safari routes and points of interest",
      "24/7 roadside assistance and recovery service",
      "Park fee payment facilitation service",
      "Vehicle orientation and basic off-road training",
      "Travel documentation package with border crossing assistance"
    ],
    excluded: [
      "Fuel consumption (approx. 12L/100km)",
      "National park entry fees (payable directly)",
      "Accommodation and meals",
      "Optional camping equipment rental ($45/day)",
      "Additional driver fees ($15/day)",
      "Cross-border permit for Tanzania ($200)",
      "Satellite phone rental ($25/day)",
      "Security deposit ($1,000 refundable)"
    ],
    ctaText: "Book Your Safari Vehicle Now",
    keywords: [
      "Toyota Prado Rental Kenya",
      "Self-Drive Safari Africa",
      "4x4 Rental Tanzania",
      "Safari Vehicle Hire",
      "Independent Safari Kenya",
      "Overland Vehicle Rental",
      "Adventure Car Hire Africa",
      "Photography Safari Vehicle"
    ],
    metaTitle: "Toyota Prado Safari Rental: Self-Drive Adventure Vehicle | Jae Travel Expeditions",
    metaDescription: "Rent a fully-equipped Toyota Prado for self-drive safaris in Kenya and Tanzania. Includes GPS, roof conversion, 24/7 support. Ultimate freedom to explore East Africa.",
    bestTime: "Dry seasons recommended for easier driving (June-October, January-February)",
    departureDates: "Daily availability with advance booking",
    accommodation: "N/A (vehicle only)",
    ageRestriction: "Minimum 25 years with valid license and 3+ years driving experience",
    sustainability: "Regularly maintained for optimal fuel efficiency, supports local mechanics network"
  },
  {
    id: "8",
    slug: "kevin",
    name: "Meet Ian: Your Safari Storyteller & Conservation Expert",
    heroImage: "/favicon.ico",
    description: "Journey with Ian, our lead guide with a decade of experience, as he shares the heart, soul, and science of East Africa's wild landscapes, intricate ecosystems, and vibrant cultures.",
    details: "Ian isn't just a guide - he's a storyteller, naturalist, and bridge between cultures. With qualifications in wildlife management, fluency in Swahili and Maa languages, and decade of guiding experience, Ian transforms ordinary safaris into extraordinary learning journeys. His approach blends scientific knowledge with ancestral wisdom learned from Maasai elders. Ian specializes in tracking predators, reading animal behavior, and explaining complex ecological relationships in accessible ways. Beyond wildlife, he facilitates genuine cultural exchanges, having built relationships with communities across Kenya and Tanzania. Ian's passion for conservation extends to mentoring young guides and supporting anti-poaching initiatives. When you travel with Ian, you gain not just a guide but a friend who opens doors to experiences most tourists never see - from private ceremonies to remote wilderness areas. His photographic memory for individual animals ensures you'll hear their life stories across your journey.",
    highlights: [
      "Personalized guiding with focus on your specific interests",
      "Tracking expertise - can identify individual animals by markings",
      "Cultural facilitator with authentic community relationships",
      "Night sky interpretation using both scientific and cultural stories",
      "Photography coaching for all skill levels",
      "Conservation storytelling that inspires action",
      "Flexible itinerary adapting to wildlife movements",
      "Access to remote areas through community permissions"
    ],
    itinerary: [
      "Pre-trip: Personalized consultation with Ian to customize your safari",
      "Day 1-2: Immersion in ecosystem dynamics with hands-on tracking lessons",
      "Day 3-4: Cultural exchanges facilitated by Ian's local relationships",
      "Day 5-6: Specialist focus (photography, birds, conservation) based on your interests",
      "Evenings: Campfire conversations about wildlife, culture, and conservation",
      "Post-trip: Continued relationship with conservation updates"
    ],
    price: 0,
    currency: "USD",
    rating: 4.8,
    reviewCount: 20,
    duration: "N/A (Ian guides multiple safari durations)",
    difficulty: "N/A",
    groupSize: "N/A",
    category: "Expert Guide Profile",
    included: [
      "Ian's guiding on select premium safaris",
      "Pre-trip planning consultation",
      "Customized wildlife checklist based on your interests",
      "Digital photo album of your safari",
      "Conservation impact report showing how your trip contributes",
      "Post-trip follow-up with wildlife updates"
    ],
    excluded: [
      "Safari costs (Ian's guiding included in premium packages)",
      "Private guiding available at additional cost",
      "Specialist workshops with Ian (photography, tracking)"
    ],
    ctaText: "Request Ian as Your Guide",
    keywords: [
      "Safari Guide Ian",
      "Expert Kenya Guide",
      "Wildlife Tracking Expert",
      "Cultural Guide Tanzania",
      "Conservation Storyteller",
      "Photography Safari Guide",
      "Maasai Culture Expert",
      "Premium Safari Guide Africa"
    ],
    metaTitle: "Meet Ian: Expert Safari Guide & Conservation Storyteller | Jae Travel Expeditions",
    metaDescription: "Travel with Ian, our expert safari guide with decade of experience. Specialist in wildlife tracking, cultural immersion, and conservation storytelling in East Africa.",
    bestTime: "Ian guides year-round; specializes in migration periods",
    departureDates: "Available on select premium safaris",
    accommodation: "N/A",
    ageRestriction: "N/A",
    sustainability: "Ian trains local guides, supports community conservation education"
  },
  {
    id: "9",
    slug: "rwanda-accessible-gorilla-safari",
    name: "Rwanda Accessible Gorilla Safari: Inclusive Adventure in Volcanoes National Park",
    heroImage: "/gorilla-trekking-experience-13.jpg",
    description: "Embark on a life-changing accessible gorilla trekking adventure in Rwanda, featuring custom-designed wheelchair vehicles, trained support teams, and tailored experiences ensuring comfort and safety for travelers with mobility challenges.",
    details: "This pioneering 5-day accessible safari makes Rwanda's incredible gorilla encounters available to everyone. We've worked with accessibility experts and the Rwanda Development Board to create an experience that maintains adventure while ensuring safety and comfort. Our custom-modified 4x4 vehicles feature wheelchair lifts, secure restraint systems, and adjustable seating. In Volcanoes National Park, trained porters and guides provide personalized assistance along accessible trails to gorilla families located in more accessible terrain. The experience includes comprehensive briefings, adaptive equipment, and flexible pacing. Beyond trekking, enjoy Kigali's wheelchair-accessible attractions including the Genocide Memorial, craft markets with ramps, and specially selected restaurants. Accommodations feature roll-in showers, grab bars, and accessible common areas. This safari represents our commitment to making Africa's wonders accessible to all travelers, with dignity and adventure intact.",
    highlights: [
      "Accessible gorilla trekking with trained support team (1 guide per traveler)",
      "Custom wheelchair-accessible vehicle with lift system",
      "Adaptive trekking equipment including all-terrain wheelchair available",
      "Accessible trails to gorilla families with gentler gradients",
      "Kigali Genocide Memorial with full accessibility features",
      "Accessible accommodations with roll-in showers and appropriate facilities",
      "Local sign language interpreter available (advance notice)",
      "Medical support team familiar with accessibility needs"
    ],
    itinerary: [
      "Day 1: Arrival Kigali International Airport with accessibility meet-and-greet. Transfer in accessible vehicle to Volcanoes area lodge. Accessibility audit of accommodations.",
      "Day 2: Accessible gorilla trekking with full support team. Flexible duration based on needs. Celebration dinner at lodge.",
      "Day 3: Golden monkey accessible trekking or cultural visit to Iby'Iwacu adapted experience. Afternoon relaxation or optional accessible activities.",
      "Day 4: Return to Kigali. Genocide Memorial visit. Accessible city tour including markets and cultural centers. Farewell dinner at accessible restaurant.",
      "Day 5: Final accessibility shopping at recommended outlets. Transfer to airport with assistance through check-in and security."
    ],
    price: 3500,
    currency: "USD",
    rating: 4.8,
    reviewCount: 8,
    duration: "5 Days / 4 Nights",
    difficulty: "Moderate (adapted to individual abilities)",
    groupSize: "Maximum 4 travelers (including wheelchair users) with 1:2 staff ratio",
    category: "Accessible & Inclusive Travel",
    included: [
      "Gorilla trekking permit for accessible trail",
      "Custom accessible 4x4 vehicle with driver-guide",
      "Two trained support staff per wheelchair user",
      "All-terrain wheelchair rental if needed",
      "Accessible lodge accommodations with required features",
      "All meals and bottled water",
      "All entrance fees and community contributions",
      "Medical support team on call 24/7",
      "Accessibility equipment transfer between locations"
    ],
    excluded: [
      "International flights",
      "Specialized personal medical equipment",
      "Personal care attendant (can be arranged)",
      "Additional accessibility equipment beyond standard",
      "Travel insurance covering pre-existing conditions",
      "Optional accessible activities beyond itinerary"
    ],
    ctaText: "Inquire About Accessible Gorilla Trekking",
    keywords: [
      "Accessible Gorilla Trekking Rwanda",
      "Wheelchair Safari Africa",
      "Disabled Friendly Gorilla Tour",
      "Accessible Volcanoes National Park",
      "Inclusive Rwanda Safari",
      "Mobility Accessible Africa Travel",
      "Adaptive Gorilla Trekking",
      "Special Needs Safari Rwanda"
    ],
    metaTitle: "Rwanda Accessible Gorilla Safari: Wheelchair-Friendly Trekking | Jae Travel Expeditions",
    metaDescription: "Fully accessible 5-day gorilla trekking safari in Rwanda. Custom vehicles, trained support team, and adapted experiences for travelers with mobility challenges. Inclusive adventure.",
    bestTime: "June-September (dry season for easier terrain)",
    departureDates: "Monthly departures with advance booking required",
    accommodation: "Specially selected accessible lodges with required features",
    ageRestriction: "Minimum 16 years for gorilla trekking",
    sustainability: "Trains and employs people with disabilities in tourism, supports accessible infrastructure development"
  },
  {
    "id": "10",
    "slug": "zanzibar-getaway",
    "name": "Zanzibar Accessible Getaway: Inclusive Beach Resort & Spice Island Discovery",
    "heroImage": "/zanzibar-accessible-beach-01.jpg",
    "description": "Relax into the rhythm of the Indian Ocean on this fully accessible Zanzibar escape. Designed for travelers with mobility devices, this tour combines beachfront wheelchair-friendly resorts, private adapted transfers, and gentle cultural tours of Stone Town and local spice farms.",
    "details": "This 5-day accessible retreat proves that paradise has no barriers. We have partnered with beachfront properties in Zanzibar that feature pool hoists, ramps to the sand, and roll-in showers with grab bars. Your journey begins with a smooth VIP accessibility transfer from Abeid Amani Karume International Airport. In Stone Town, we navigate the narrow streets with adapted vehicles and trained guides, ensuring visits to the Old Fort and Forodhani Gardens are stress-free. The highlight is a private, accessible Spice Tour where raised garden beds and paved pathways allow wheelchair users to smell, touch, and taste Zanzibar’s famous cloves and vanilla without leaving their chairs. Unlike standard tours, our beach days include accessible dhows (traditional boats) for sunset cruises and adaptive water sports equipment. This itinerary is slow-paced, focused on rest, dignity, and genuine cultural immersion.",
    "highlights": [
      "Fully accessible beachfront resort with pool hoist and beach wheelchair available",
      "Private accessible spice tour with raised garden viewing platforms",
      "Stone Town accessible heritage walk (flat-route adaptation)",
      "Sunset dhow cruise with wheelchair boarding ramp",
      "Airport accessibility concierge upon arrival",
      "Specialized accessible transfer van with lift",
      "Swahili cooking class adapted for wheelchair users",
      "Visit to local artisan workshops with step-free access"
    ],
    "itinerary": [
      "Day 1: Arrival Zanzibar (ZNZ). Accessibility meet-and-assist. Transfer in wheelchair lift-equipped van to Nungwi accessible resort. Resort accessibility orientation and welcome dinner.",
      "Day 2: Morning leisure at beachfront accessible pool. Optional adaptive snorkeling (advance notice). Afternoon private accessible Spice Tour with paved pathways and planting beds at viewing height.",
      "Day 3: Transfer to Stone Town. Accessible city tour: Forodhani Gardens, Old Fort (ramp access), and House of Wonders exterior viewing. Evening accessible dhow cruise with adapted boarding.",
      "Day 4: Swahili cooking class at accessible community center (adapted workstations). Farewell beachside dinner with live music.",
      "Day 5: Accessible souvenir shopping. Private transfer to airport with full assistance through check-in and security."
    ],
    "price": 2900,
    "currency": "USD",
    "rating": 4.9,
    "reviewCount": 12,
    "duration": "5 Days / 4 Nights",
    "difficulty": "Easy (Accessible for all mobility levels)",
    "groupSize": "Private Tour: 1-6 travelers (wheelchair accessible vehicle)",
    "category": "Accessible Beach & Cultural Retreat",
    "included": [
      "4 nights accessible beachfront/lodge accommodation",
      "Daily breakfast and half-board dinners",
      "Private wheelchair-accessible vehicle with lift",
      "Accessibility-trained English-speaking guide",
      "Stone Town accessible heritage tour",
      "Private spice tour (accessible route)",
      "Sunset dhow cruise (wheelchair accessible boat)",
      "All park fees and community tourism levies",
      "24/7 in-country accessibility support hotline"
    ],
    "excluded": [
      "International and domestic flights",
      "Travel insurance (highly recommended)",
      "Personal care assistant (can be arranged)",
      "Alcoholic beverages and premium imported drinks",
      "Tips and gratuities for staff",
      "Adaptive snorkeling/scuba equipment"
    ],
    "ctaText": "Plan Your Accessible Island Escape",
    "keywords": [
      "Accessible Zanzibar Beach Holiday",
      "Wheelchair Friendly Safari Zanzibar",
      "Disabled Travel Tanzania Island",
      "Adaptive Spice Tour Zanzibar",
      "Inclusive Beach Resort Tanzania",
      "Mobility Accessible Stone Town",
      "Zanzibar for Elderly Travelers",
      "Accessible Dhow Cruise"
    ],
    "metaTitle": "Zanzibar Accessible Beach & Spice Tour: Wheelchair-Friendly | Jae Travel Expeditions",
    "metaDescription": "Discover accessible Zanzibar: Beach wheelchairs, adapted spice tours, and step-free Stone Town visits. Inclusive luxury with private transfers and trained support staff.",
    "bestTime": "June-October & December-February (Dry, cooler months for easy mobility)",
    "departureDates": "Daily departures; private tours available year-round",
    "accommodation": "Selected accessible resorts in Nungwi and Stone Town with verified roll-in showers, pool hoists, and step-free access",
    "ageRestriction": "No age restriction; family-friendly",
    "sustainability": "Partners with inclusive Zanzibar cooperatives and employs guides with disabilities; supports accessible tourism certification initiatives in Tanzania"
  },
  {
    "id": "11",
    "slug": "best-of-kenya-tanzania-3",
    "name": "Best of Kenya & Tanzania Accessible Safari: Maasai Mara to Serengeti",
    "heroImage": "/wheelchair-safari-east-africa-07.jpg",
    "description": "The ultimate East African accessible adventure crossing two countries. From the Maasai Mara to the Serengeti and Ngorongoro Crater, this safari features wheelchair-modified safari vehicles, accessible lodges, and expert guides trained in inclusive travel.",
    "details": "This 10-day cross-border safari proves that the Great Migration is for everyone. We utilize custom 4x4 safari vehicles with roof hatches adapted for wheelchair users, providing unobstructed photography and game viewing. Our routes include accessible airstrips and lodges with step-free tented suites, portable ramps, and vibrating pillow alerts for hearing-impaired guests. In the Maasai Mara, we visit accessible viewpoints and offer flexible game drives without time constraints. Crossing to Tanzania, the Serengeti Visitor Centre features paved walkways. The Ngorongoro Crater floor offers the highest concentration of wildlife and our vehicles are equipped to handle the descent safely. We provide private accessible picnic sites and consider dietary restrictions carefully. This tour includes a dedicated accessibility coordinator who handles border crossings seamlessly, ensuring travelers focus solely on the magic of the savannah.",
    "highlights": [
      "Custom safari vehicle with wheelchair lift and 360° viewing platform",
      "Accessible game drives in Maasai Mara, Serengeti & Ngorongoro",
      "Step-free luxury tented camps with roll-in showers",
      "Accessible hot air balloon safari option (advance request)",
      "Vibrating alert systems for hearing-impaired travelers",
      "Private border crossing assistance (Kenya/Tanzania)",
      "Wheelchair-accessible picnic lunches in the bush",
      "Cultural visit to accessible Maasai village (adapted experience)"
    ],
    "itinerary": [
      "Day 1: Arrival Nairobi (NBO). Accessible transfer to Nairobi accessible hotel. Safari briefing with accessibility team.",
      "Day 2: Fly to Maasai Mara (wheelchair assistance at Wilson Airport). Afternoon accessible game drive in modified 4x4.",
      "Day 3: Full day Maasai Mara. Private accessible picnic site. Flexible game drive duration. Optional accessible balloon safari.",
      "Day 4: Fly to Lake Manyara (Tanzania). Accessible border transfer. Evening game drive.",
      "Day 5: Lake Manyara National Park. Paved accessible hippo pool and tree-top viewing platforms.",
      "Day 6-7: Serengeti National Park (central). Accessible visitor center and wheelchair-friendly kopje viewpoints.",
      "Day 8: Ngorongoro Crater descent. Game drive on crater floor. Adapted lunch at accessible picnic site.",
      "Day 9: Return to Arusha. Accessible city tour and Tanzanite shopping (step-free outlets). Farewell cultural dinner.",
      "Day 10: Transfer to Kilimanjaro Airport (JRO) with full accessibility assistance."
    ],
    "price": 8950,
    "currency": "USD",
    "rating": 5.0,
    "reviewCount": 6,
    "duration": "10 Days / 9 Nights",
    "difficulty": "Moderate (adapted with all-terrain equipment and flexible pacing)",
    "groupSize": "Maximum 4 travelers (exclusively for wheelchair users/families)",
    "category": "Premium Accessible Wildlife Safari",
    "included": [
      "All domestic flights in Kenya & Tanzania with wheelchair assistance",
      "9 nights accessible luxury lodges and tented camps",
      "Private accessible safari vehicle with pop-up roof and lift",
      "Services of a dedicated accessibility safari guide",
      "All park fees, crater service fees, and government taxes",
      "Maasai Mara & Serengeti game drives as per itinerary",
      "All meals and non-alcoholic beverages",
      "Private border crossing facilitation",
      "Wheelchair repair kit and backup vehicle support",
      "Emergency evacuation insurance coverage"
    ],
    "excluded": [
      "International flights",
      "Premier alcoholic beverages",
      "Visa fees (Kenya & Tanzania E-Visa)",
      "Personal shopping and souvenirs",
      "Personal care attendant (arranged on request)",
      "Travel insurance (mandatory)"
    ],
    "ctaText": "Request Your Cross-Border Accessible Safari",
    "keywords": [
      "Accessible Kenya Tanzania Safari",
      "Wheelchair Safari Maasai Mara",
      "Disabled Travel Serengeti",
      "Adapted Ngorongoro Crater Tour",
      "Inclusive East Africa Safari",
      "Mobility Accessible Safari Vehicle",
      "Special Needs Safari Kenya Tanzania",
      "Wheelchair Friendly Migration Safari"
    ],
    "metaTitle": "Best of Kenya & Tanzania Accessible Safari: Maasai Mara to Serengeti | Jae Travel Expeditions",
    "metaDescription": "Experience the Great Migration on this fully accessible Kenya-Tanzania safari. Modified 4x4 vehicles, step-free lodges, and expert guides trained in inclusive travel.",
    "bestTime": "June-October (Dry season, optimal for vehicle access and wildlife viewing)",
    "departureDates": "Guaranteed accessible departures: Jan 15, Jun 10, Jul 22, Aug 14, Sep 5, Dec 1 (private dates available)",
    "accommodation": "Verified accessible lodges and tented camps with roll-in showers, raised beds for ease of transfer, and paved pathways",
    "ageRestriction": "Minimum 12 years (younger considered on private basis)",
    "sustainability": "Supports Inclusive Safari Guide Training Program; donates portion of proceeds to East African disability advocacy groups; employs guides with physical disabilities in community tourism roles"
  }
];