import { ReactNode } from "react";

export interface Tour {
  shortDescription: string;
  image: string;
  duration: ReactNode;
  highlights: any;
  included: any;
  excluded: any;
  difficulty: any;
  groupSize: ReactNode;
  category: ReactNode;
  internalLinks?: Array<{ url: string; label: string }>
  metaTitle: string
  metaDescription?: string
  keywords?: string | string[]
  url: string
  id: string
  slug: string
  title: string
  description: string
  price: number
  currency: string
  rating: number
  reviewCount: number
  itinerary: string
  bookingUrl: string
  region: string
  country: string
  isOnOffer?: boolean
  originalPrice?: number
  postId?: string; // Added for query-based posts
}

export const tours: Tour[] = [
  {
    id: "kenya-masai-mara",
    slug: "masai-mara-luxury-safari",
    image: "/masai-mara-migration.jpg",
    title: "Masai Mara Luxury Safari",
    description: "Experience the wildlife of Masai Mara with luxury accommodations and expert guides. Includes game drives and meals.",
    price: 3500,
    currency: "USD",
    rating: 4.8,
    reviewCount: 128,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Morning and evening game drives. Day 3: Optional hot air balloon ride and departure.",
    bookingUrl: "/booking/masai-mara-luxury-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Masai Mara Luxury Safari | Jae Travel Expeditions",
    metaDescription: "Book your Masai Mara Luxury Safari with Jae Travel. Enjoy game drives, luxury lodges, and expert guides in Kenya's most iconic park.",
    keywords: ["Masai Mara Safari", "Luxury Kenya Safari", "Kenya Wildlife Tours"],
    url: "/tours/masai-mara-luxury-safari",
    isOnOffer: true,
    originalPrice: 4200,
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "kenya-amboseli",
    slug: "amboseli-safari",
    image: "/Amboseli-National-Park-Elephantsssss.jpg",
    title: "Amboseli Safari Adventure",
    description: "Explore Amboseli National Park with guided game drives and spectacular views of Mount Kilimanjaro.",
    price: 2800,
    currency: "USD",
    rating: 4.7,
    reviewCount: 95,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Morning and evening game drives. Day 3: Departure.",
    bookingUrl: "/booking/amboseli-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Amboseli Safari Adventure | Jae Travel Expeditions",
    metaDescription: "Discover Amboseli Safari with breathtaking views of Mount Kilimanjaro. Guided game drives and luxury stays included.",
    keywords: ["Amboseli Safari", "Kenya Tours", "Kilimanjaro Safari"],
    url: "/tours/amboseli-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "tanzania-serengeti",
    slug: "serengeti-migration-tour",
    image: "/Serengeti-National-Park-Africa-Kenya-Safaris2.jpg",
    title: "Serengeti Migration Safari",
    description: "Witness the Great Migration in Serengeti with guided tours and comfortable lodges. Includes daily game drives and meals.",
    price: 4200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 97,
    itinerary: "Day 1: Arrival in Serengeti. Day 2-3: Game drives tracking the migration. Day 4: Cultural visit and departure.",
    bookingUrl: "/booking/serengeti-migration-tour",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Serengeti Migration Safari | Jae Travel Expeditions",
    metaDescription: "Experience the Great Migration in Serengeti with expert guides, luxury lodges, and unforgettable wildlife encounters.",
    keywords: ["Serengeti Migration", "Tanzania Safari", "Great Migration Tour"],
    url: "/tours/serengeti-migration-tour",
    isOnOffer: true,
    originalPrice: 5000,
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "tanzania-ngorongoro",
    slug: "ngorongoro-crater-safari",
    image: "/Ngorongoro-Crater.jpg",
    title: "Ngorongoro Crater Safari",
    description: "Explore the Ngorongoro Crater with guided game drives and luxury accommodation. Ideal for families and photographers.",
    price: 2800,
    currency: "USD",
    rating: 4.7,
    reviewCount: 64,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Full-day game drive in the crater. Day 3: Departure.",
    bookingUrl: "/booking/ngorongoro-crater-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Ngorongoro Crater Safari | Jae Travel Expeditions",
    metaDescription: "Book your Ngorongoro Crater Safari with Jae Travel. A perfect adventure for families, photographers, and nature lovers.",
    keywords: ["Ngorongoro Safari", "Tanzania Wildlife Tours", "Family Safari"],
    url: "/tours/ngorongoro-crater-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "uganda-bwindi",
    slug: "bwindi-gorilla-trek",
    image: "/bwindi-forest-uganda-gorilla-safaris.jpg",
    title: "Bwindi Gorilla Trekking",
    description: "Trek the dense forests of Bwindi to see mountain gorillas up close with expert guides. Includes park fees and accommodations.",
    price: 3200,
    currency: "USD",
    rating: 4.8,
    reviewCount: 80,
    itinerary: "Day 1: Arrival at lodge. Day 2: Gorilla trekking experience. Day 3: Cultural visit and departure.",
    bookingUrl: "/booking/bwindi-gorilla-trek",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Bwindi Gorilla Trekking | Jae Travel Expeditions",
    metaDescription: "Embark on a Bwindi Gorilla Trekking safari. See mountain gorillas up close and explore Uganda's lush forests.",
    keywords: ["Bwindi Gorilla Trek", "Uganda Safari", "Gorilla Trekking Tours"],
    url: "/tours/bwindi-gorilla-trek",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "rwanda-volcanoes",
    slug: "volcanoes-national-park-safari",
    image: "/Volcanoes-National-Park-Rwanda-Natural-World-Kenya-Safaris.jpg",
    title: "Rwanda Gorilla Safari",
    description: "Explore Volcanoes National Park in Rwanda to trek gorillas and experience local culture.",
    price: 3800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 72,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Gorilla trekking. Day 3: Cultural tour and departure.",
    bookingUrl: "/booking/volcanoes-national-park-safari",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Rwanda Gorilla Safari | Jae Travel Expeditions",
    metaDescription: "Book your Rwanda Gorilla Safari in Volcanoes National Park. Trek gorillas, enjoy cultural tours, and luxury accommodations.",
    keywords: ["Rwanda Gorilla Safari", "Volcanoes National Park", "Gorilla Trekking Rwanda"],
    url: "/tours/volcanoes-national-park-safari",
    isOnOffer: true,
    originalPrice: 4500,
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "1",
    slug: "masai-mara-safari-adventure",
    image: "/magestic-maasai-serengeti.jpg",
    title: "Masai Mara Safari Adventure",
    description: "Experience the great migration and witness the Big Five in Kenya's most iconic national reserve.",
    price: 1200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 156,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-4: Morning and evening game drives. Day 5: Departure.",
    bookingUrl: "/booking/masai-mara-safari-adventure",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Masai Mara Safari Adventure - 5 Days | Jae Travel Expeditions",
    metaDescription: "Experience the great migration and witness the Big Five in Masai Mara. 5-day safari with expert guides, luxury lodges, and unforgettable wildlife encounters.",
    keywords: ["Masai Mara", "Kenya Safari", "Big Five", "Great Migration", "Wildlife Safari"],
    url: "/tours/masai-mara-safari-adventure",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "2",
    slug: "amboseli-elephant-safari",
    image: "/amboseli-elephants-00007.jpg",
    title: "Amboseli Elephant Safari",
    description: "Get close to elephants with Mount Kilimanjaro backdrop in Amboseli National Park.",
    price: 980,
    currency: "USD",
    rating: 4.7,
    reviewCount: 89,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-3: Game drives and elephant viewing. Day 4: Departure.",
    bookingUrl: "/booking/amboseli-elephant-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Amboseli Elephant Safari - 4 Days | Jae Travel Expeditions",
    metaDescription: "Get close to elephants with Mount Kilimanjaro backdrop. 4-day Amboseli safari with spectacular views and abundant wildlife.",
    keywords: ["Amboseli", "Elephant Safari", "Kilimanjaro", "Kenya Wildlife"],
    url: "/tours/amboseli-elephant-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "3",
    slug: "samburu-game-reserve",
    image: "/Samburu_National_Reserve,_Kenya-26December2012.jpg",
    title: "Samburu Game Reserve",
    description: "Discover unique wildlife in the northern frontier.",
    price: 750,
    currency: "USD",
    rating: 4.6,
    reviewCount: 45,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Full-day game drives. Day 3: Departure.",
    bookingUrl: "/booking/samburu-game-reserve",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Samburu Game Reserve Safari - 3 Days | Jae Travel Expeditions",
    metaDescription: "Discover unique wildlife in the northern frontier of Kenya at Samburu Game Reserve. See rare species like Grevy's zebra and reticulated giraffe.",
    keywords: ["Samburu", "Game Reserve", "Northern Kenya", "Unique Wildlife"],
    url: "/tours/samburu-game-reserve",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "4",
    slug: "lake-nakuru-flamingo-spectacle",
    image: "/lake-nakuru-flamingos-in-red-sunset-590x390.jpg",
    title: "Lake Nakuru Flamingo Tour",
    description: "Witness thousands of flamingos in their natural habitat.",
    price: 450,
    currency: "USD",
    rating: 4.5,
    reviewCount: 67,
    itinerary: "Day 1: Arrival and afternoon game drive. Day 2: Morning bird watching and departure.",
    bookingUrl: "/booking/lake-nakuru-flamingo-spectacle",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Lake Nakuru Flamingo Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Witness thousands of flamingos in their natural habitat at Lake Nakuru. Perfect for bird watchers and photographers.",
    keywords: ["Lake Nakuru", "Flamingos", "Bird Watching", "Kenya"],
    url: "/tours/lake-nakuru-flamingo-spectacle",
    isOnOffer: true,
    originalPrice: 550,
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "5",
    slug: "tsavo-east-west-adventure",
    image: "/tsavo-west-national-park-chyulu-gate.jpg.webp",
    title: "Tsavo East & West Safari",
    description: "Explore Kenya's largest national park.",
    price: 1350,
    currency: "USD",
    rating: 4.8,
    reviewCount: 73,
    itinerary: "Day 1: Arrival at Tsavo East. Day 2-3: Game drives in Tsavo East. Day 4-5: Transfer to Tsavo West and game drives. Day 6: Departure.",
    bookingUrl: "/booking/tsavo-east-west-adventure",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Tsavo East & West Safari - 6 Days | Jae Travel Expeditions",
    metaDescription: "Explore Kenya's largest national park with our Tsavo East & West Safari. See red elephants, diverse landscapes, and abundant wildlife.",
    keywords: ["Tsavo", "National Park", "Kenya Safari", "Red Elephants"],
    url: "/tours/tsavo-east-west-adventure",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "6",
    slug: "mombasa-coastal-safari",
    image: "/Mombasa-beach-2-1960x800.webp",
    title: "Mombasa Beach & Safari",
    description: "Combine safari adventures with beach relaxation.",
    price: 1600,
    currency: "USD",
    rating: 4.7,
    reviewCount: 91,
    itinerary: "Day 1-3: Safari in Tsavo East. Day 4-7: Beach relaxation in Mombasa with optional water sports and cultural tours.",
    bookingUrl: "/booking/mombasa-coastal-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Mombasa Beach & Safari - 7 Days | Jae Travel Expeditions",
    metaDescription: "Combine safari adventures with beach relaxation on our Mombasa Beach & Safari package. Perfect blend of wildlife and coastal paradise.",
    keywords: ["Mombasa", "Beach Safari", "Coastal Kenya", "Safari and Beach"],
    url: "/tours/mombasa-coastal-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "7",
    slug: "mount-kenya-climbing-expedition",
    image: "/mt-kenya.jpg",
    title: "Mount Kenya Climbing",
    description: "Challenge yourself with Africa's second highest peak.",
    price: 1100,
    currency: "USD",
    rating: 4.4,
    reviewCount: 38,
    itinerary: "Day 1: Arrival and briefing. Day 2-4: Climbing expedition to Point Lenana. Day 5: Descent and departure.",
    bookingUrl: "/booking/mount-kenya-climbing-expedition",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Mount Kenya Climbing Expedition - 5 Days | Jae Travel Expeditions",
    metaDescription: "Challenge yourself with Africa's second highest peak on our Mount Kenya climbing expedition. Reach Point Lenana with expert guides.",
    keywords: ["Mount Kenya", "Climbing", "Trekking", "Mountain Expedition"],
    url: "/tours/mount-kenya-climbing-expedition",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "8",
    slug: "laikipia-conservancy",
    image: "/laikipia-kenya-photography-safari.jpg",
    title: "Laikipia Conservancy",
    description: "Experience conservation in action.",
    price: 1250,
    currency: "USD",
    rating: 4.8,
    reviewCount: 52,
    itinerary: "Day 1: Arrival and orientation. Day 2-3: Game drives, conservation activities, and community visits. Day 4: Departure.",
    bookingUrl: "/booking/laikipia-conservancy",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Laikipia Conservancy Experience - 4 Days | Jae Travel Expeditions",
    metaDescription: "Experience conservation in action at Laikipia Conservancy. Engage with wildlife protection efforts and community development.",
    keywords: ["Laikipia", "Conservancy", "Conservation", "Community Tourism"],
    url: "/tours/laikipia-conservancy",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "9",
    slug: "hell-gate-lake-naivasha-adventure",
    image: "/Hells-Gate-National-Park.jpg",
    title: "Hell's Gate Adventure",
    description: "Bike and hike through dramatic landscapes.",
    price: 380,
    currency: "USD",
    rating: 4.3,
    reviewCount: 84,
    itinerary: "Day 1: Biking in Hell's Gate and gorge hiking. Day 2: Boat safari on Lake Naivasha and departure.",
    bookingUrl: "/booking/hell-gate-lake-naivasha-adventure",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Hell's Gate Adventure Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Bike and hike through dramatic landscapes at Hell's Gate National Park. Unique safari experience with cycling and gorge exploration.",
    keywords: ["Hell's Gate", "Adventure", "Biking", "Lake Naivasha"],
    url: "/tours/hell-gate-lake-naivasha-adventure",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "10",
    slug: "maasai-cultural-experience",
    image: "/magestic-maasai-serengeti.jpg",
    title: "Maasai Cultural Experience",
    description: "Immerse yourself in Maasai culture.",
    price: 650,
    currency: "USD",
    rating: 4.6,
    reviewCount: 96,
    itinerary: "Day 1: Arrival and welcome ceremony. Day 2: Cultural activities, traditional dances, and village tour. Day 3: Departure.",
    bookingUrl: "/booking/maasai-cultural-experience",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Maasai Cultural Experience - 3 Days | Jae Travel Expeditions",
    metaDescription: "Immerse yourself in Maasai culture with our authentic cultural experience. Learn traditions, participate in ceremonies, and stay in a Maasai village.",
    keywords: ["Maasai", "Cultural Experience", "Kenya Culture", "Traditional Village"],
    url: "/tours/maasai-cultural-experience",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "11",
    slug: "aberdare-national-park-safari",
    image: "/Aberdare.jpg",
    title: "Aberdare National Park",
    description: "Mountain forest safari experience.",
    price: 720,
    currency: "USD",
    rating: 4.5,
    reviewCount: 41,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Forest walks and game viewing. Day 3: Departure.",
    bookingUrl: "/booking/aberdare-national-park-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Aberdare National Park Safari - 3 Days | Jae Travel Expeditions",
    metaDescription: "Experience a mountain forest safari in Aberdare National Park. See rare bongo antelopes, elephants, and stunning waterfalls.",
    keywords: ["Aberdare", "National Park", "Mountain Safari", "Forest Wildlife"],
    url: "/tours/aberdare-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "12",
    slug: "diani-beach-safari-combo",
    image: "/Kenia-Mombasa-Diani-Beach-Leopard-Beach-Resort-strand-long-beach-LBR_1.jpg",
    title: "Diani Beach Safari Combo",
    description: "Ultimate Kenya safari and beach experience.",
    price: 1800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 108,
    itinerary: "Day 1-4: Safari in Tsavo West. Day 5-8: Beach relaxation at Diani Beach with snorkeling, diving, and cultural tours.",
    bookingUrl: "/booking/diani-beach-safari-combo",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Diani Beach Safari Combo - 8 Days | Jae Travel Expeditions",
    metaDescription: "Experience the ultimate Kenya safari and beach experience at Diani Beach. Perfect combination of wildlife adventures and tropical paradise.",
    keywords: ["Diani Beach", "Beach Safari", "Kenya Coast", "Safari Beach Combo"],
    url: "/tours/diani-beach-safari-combo",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "13",
    slug: "serengeti-wildlife-safari",
    image: "/serengeti-day-trip.jpeg",
    title: "Serengeti Wildlife Safari",
    description: "Explore the endless plains of Serengeti and witness incredible wildlife diversity.",
    price: 1800,
    currency: "USD",
    rating: 4.8,
    reviewCount: 142,
    itinerary: "Day 1: Arrival in Arusha. Day 2-6: Serengeti game drives tracking wildlife. Day 7: Departure via Arusha.",
    bookingUrl: "/booking/serengeti-wildlife-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Serengeti Wildlife Safari - 7 Days | Jae Travel Expeditions",
    metaDescription: "Explore the endless plains of Serengeti on a 7-day wildlife safari. Experience incredible biodiversity and stunning landscapes.",
    keywords: ["Serengeti", "Wildlife Safari", "Tanzania", "African Safari", "Big Five"],
    url: "/tours/serengeti-wildlife-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "14",
    slug: "ngorongoro-crater-tour",
    image: "/Ngorongoro-Crater.jpg",
    title: "Ngorongoro Crater Tour",
    description: "Visit the world's largest intact caldera.",
    price: 950,
    currency: "USD",
    rating: 4.9,
    reviewCount: 118,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Full-day crater tour. Day 3: Departure.",
    bookingUrl: "/booking/ngorongoro-crater-tour",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Ngorongoro Crater Tour - 3 Days | Jae Travel Expeditions",
    metaDescription: "Visit the world's largest intact caldera at Ngorongoro Crater. Witness dense wildlife populations in this natural wonder.",
    keywords: ["Ngorongoro", "Crater", "Caldera", "Tanzania Safari"],
    url: "/tours/ngorongoro-crater-tour",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "15",
    slug: "kilimanjaro-climbing-expedition",
    image: "/kilimanjaro-moutain-climbing.jpg",
    title: "Kilimanjaro Climbing",
    description: "Conquer Africa's highest peak.",
    price: 2200,
    currency: "USD",
    rating: 4.7,
    reviewCount: 76,
    itinerary: "Day 1: Arrival and briefing. Day 2-7: Climbing via Machame Route. Day 8: Summit day and descent. Day 9: Departure.",
    bookingUrl: "/booking/kilimanjaro-climbing-expedition",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Kilimanjaro Climbing Expedition - 9 Days | Jae Travel Expeditions",
    metaDescription: "Conquer Africa's highest peak on our Mount Kilimanjaro climbing expedition. Reach Uhuru Peak with experienced guides.",
    keywords: ["Kilimanjaro", "Climbing", "Trekking", "Summit", "Machame Route"],
    url: "/tours/kilimanjaro-climbing-expedition",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "16",
    slug: "tarangire-national-park-safari",
    image: "/boabab-tarangire-national-park.jpg",
    title: "Tarangire Elephant Safari",
    description: "See large herds of elephants.",
    price: 1100,
    currency: "USD",
    rating: 4.6,
    reviewCount: 63,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-3: Game drives focusing on elephants. Day 4: Departure.",
    bookingUrl: "/booking/tarangire-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Tarangire Elephant Safari - 4 Days | Jae Travel Expeditions",
    metaDescription: "See large herds of elephants in Tarangire National Park. Famous for its elephant population and ancient baobab trees.",
    keywords: ["Tarangire", "Elephant Safari", "Tanzania", "Baobab Trees"],
    url: "/tours/tarangire-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "17",
    slug: "lake-manyara-national-park-safari",
    image: "/Lake Manyara banner.jpg",
    title: "Lake Manyara Tree Climbing Lions",
    description: "Witness unique tree-climbing lions.",
    price: 580,
    currency: "USD",
    rating: 4.4,
    reviewCount: 54,
    itinerary: "Day 1: Arrival and afternoon game drive. Day 2: Morning game drive and departure.",
    bookingUrl: "/booking/lake-manyara-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Lake Manyara Tree Climbing Lions Safari - 2 Days | Jae Travel Expeditions",
    metaDescription: "Witness unique tree-climbing lions in Lake Manyara National Park. Compact park with diverse ecosystems and abundant birdlife.",
    keywords: ["Lake Manyara", "Tree Climbing Lions", "Tanzania Safari", "Bird Watching"],
    url: "/tours/lake-manyara-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "18",
    slug: "zanzibar-beach-holiday",
    image: "/zanzibar-stone-town-view-min-800x600.jpg",
    title: "Zanzibar Spice Island",
    description: "Explore the spice island paradise.",
    price: 1300,
    currency: "USD",
    rating: 4.8,
    reviewCount: 134,
    itinerary: "Day 1: Arrival and Stone Town tour. Day 2-4: Beach relaxation, spice tours, and water sports. Day 5: Departure.",
    bookingUrl: "/booking/zanzibar-beach-holiday",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Zanzibar Spice Island Holiday - 5 Days | Jae Travel Expeditions",
    metaDescription: "Explore the spice island paradise of Zanzibar. White sand beaches, historic Stone Town, and aromatic spice plantations.",
    keywords: ["Zanzibar", "Spice Island", "Beach Holiday", "Stone Town", "Tanzania Coast"],
    url: "/tours/zanzibar-beach-holiday",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "19",
    slug: "ruaha-national-park-safari",
    image: "/ruaha-national-park-featured.jpg",
    title: "Ruaha National Park",
    description: "Tanzania's largest national park.",
    price: 1450,
    currency: "USD",
    rating: 4.5,
    reviewCount: 47,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-5: Game drives in Ruaha. Day 6: Departure.",
    bookingUrl: "/booking/ruaha-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Ruaha National Park Safari - 6 Days | Jae Travel Expeditions",
    metaDescription: "Explore Tanzania's largest national park at Ruaha. Remote wilderness with large elephant populations and diverse predators.",
    keywords: ["Ruaha", "National Park", "Tanzania Safari", "Wilderness"],
    url: "/tours/ruaha-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "20",
    slug: "selous-game-reserve-safari",
    image: "/SELOUS-GAME-RESERVE.jpg",
    title: "Selous Game Reserve",
    description: "Africa's largest game reserve.",
    price: 1350,
    currency: "USD",
    rating: 4.7,
    reviewCount: 59,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-4: Game drives and boat safaris. Day 5: Departure.",
    bookingUrl: "/booking/selous-game-reserve-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Selous Game Reserve Safari - 5 Days | Jae Travel Expeditions",
    metaDescription: "Explore Africa's largest game reserve at Selous. Boat safaris on the Rufiji River and walking safaris available.",
    keywords: ["Selous", "Game Reserve", "Tanzania", "Boat Safari", "Walking Safari"],
    url: "/tours/selous-game-reserve-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "21",
    slug: "mikumi-national-park",
    image: "/Mikumi2017.jpg",
    title: "Mikumi National Park",
    description: "Accessible wildlife viewing.",
    price: 750,
    currency: "USD",
    rating: 4.3,
    reviewCount: 42,
    itinerary: "Day 1: Arrival and afternoon game drive. Day 2: Full-day game drive. Day 3: Departure.",
    bookingUrl: "/booking/mikumi-national-park",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Mikumi National Park Safari - 3 Days | Jae Travel Expeditions",
    metaDescription: "Enjoy accessible wildlife viewing in Mikumi National Park. Close to Dar es Salaam with abundant wildlife.",
    keywords: ["Mikumi", "National Park", "Wildlife Viewing", "Tanzania"],
    url: "/tours/mikumi-national-park",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "22",
    slug: "arusha-cultural-tour",
    image: "/Cultural-Heritage-Centre-Arusha-Tanzania.jpg",
    title: "Arusha Cultural Tour",
    description: "Experience local Tanzanian culture.",
    price: 420,
    currency: "USD",
    rating: 4.2,
    reviewCount: 38,
    itinerary: "Day 1: City tour and cultural center visits. Day 2: Maasai village visit and departure.",
    bookingUrl: "/booking/arusha-cultural-tour",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Arusha Cultural Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Experience local Tanzanian culture in Arusha. Visit markets, cultural centers, and traditional Maasai villages.",
    keywords: ["Arusha", "Cultural Tour", "Tanzania Culture", "Maasai Village"],
    url: "/tours/arusha-cultural-tour",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "23",
    slug: "katavi-national-park-safari",
    image: "/Katavi-National-Park-600x400.png",
    title: "Katavi National Park",
    description: "Remote wilderness experience.",
    price: 1600,
    currency: "USD",
    rating: 4.6,
    reviewCount: 31,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-3: Game drives in remote wilderness. Day 4: Departure.",
    bookingUrl: "/booking/katavi-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Katavi National Park Safari - 4 Days | Jae Travel Expeditions",
    metaDescription: "Experience remote wilderness in Katavi National Park. One of Tanzania's most untouched safari destinations.",
    keywords: ["Katavi", "National Park", "Wilderness", "Remote Safari", "Tanzania"],
    url: "/tours/katavi-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "24",
    slug: "mahale-mountains-national-park-chimpanzee-trekking",
    image: "/Chimp-Group-Mahale-Mountain-JEP_8612.jpg",
    title: "Mahale Chimpanzee Trek",
    description: "Trek with wild chimpanzees.",
    price: 2100,
    currency: "USD",
    rating: 4.9,
    reviewCount: 44,
    itinerary: "Day 1: Arrival at Lake Tanganyika. Day 2-5: Chimpanzee trekking in Mahale Mountains. Day 6: Departure.",
    bookingUrl: "/booking/mahale-mountains-national-park-chimpanzee-trekking",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Mahale Chimpanzee Trek - 6 Days | Jae Travel Expeditions",
    metaDescription: "Trek with wild chimpanzees in Mahale Mountains National Park. Remote paradise on Lake Tanganyika shores.",
    keywords: ["Mahale", "Chimpanzee Trek", "Tanzania", "Lake Tanganyika", "Primate Trekking"],
    url: "/tours/mahale-mountains-national-park-chimpanzee-trekking",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "25",
    slug: "pemba-island-diving",
    image: "/Pemba-Island-15.jpg",
    title: "Pemba Island Diving",
    description: "World-class diving experience.",
    price: 980,
    currency: "USD",
    rating: 4.5,
    reviewCount: 56,
    itinerary: "Day 1: Arrival and orientation. Day 2-3: Diving expeditions. Day 4: Departure.",
    bookingUrl: "/booking/pemba-island-diving",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Pemba Island Diving - 4 Days | Jae Travel Expeditions",
    metaDescription: "Experience world-class diving in Pemba Island. Pristine coral reefs, diverse marine life, and crystal-clear waters.",
    keywords: ["Pemba Island", "Diving", "Scuba Diving", "Tanzania", "Coral Reefs"],
    url: "/tours/pemba-island-diving",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "26",
    slug: "stone-town-heritage-tour",
    image: "/31719088_tourists-on-a-typical-narrow-street-in-stone-town-zanzibar-e1713023620250.jpg",
    title: "Stone Town Heritage Tour",
    description: "Explore UNESCO World Heritage site.",
    price: 350,
    currency: "USD",
    rating: 4.4,
    reviewCount: 72,
    itinerary: "Day 1: Guided walking tour of Stone Town. Day 2: Spice tour and departure.",
    bookingUrl: "/booking/stone-town-heritage-tour",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Stone Town Heritage Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Explore UNESCO World Heritage site in Stone Town, Zanzibar. Historic architecture, spice markets, and Swahili culture.",
    keywords: ["Stone Town", "Heritage Tour", "UNESCO", "Zanzibar", "Cultural Tour"],
    url: "/tours/stone-town-heritage-tour",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "27",
    slug: "northern-circuit-safari",
    image: "/Game-Drive-north-of-Serengeti-National-Park.jpg",
    title: "Northern Circuit Safari",
    description: "Complete northern Tanzania experience.",
    price: 2800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 87,
    itinerary: "Day 1: Arrival in Arusha. Day 2-4: Serengeti. Day 5-6: Ngorongoro Crater. Day 7-8: Tarangire. Day 9-10: Lake Manyara and departure.",
    bookingUrl: "/booking/northern-circuit-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Northern Circuit Safari - 10 Days | Jae Travel Expeditions",
    metaDescription: "Experience the complete northern Tanzania safari circuit. Visit Serengeti, Ngorongoro, Tarangire, and Lake Manyara.",
    keywords: ["Northern Circuit", "Tanzania Safari", "Comprehensive Safari", "Multi-Park Safari"],
    url: "/tours/northern-circuit-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "28",
    slug: "gorilla-trekking-experience",
    image: "/gorilla-trekking-experience-13.jpg",
    title: "Rwanda Gorilla Trekking Experience",
    description: "Get up close with mountain gorillas in Volcanoes National Park, Rwanda.",
    price: 2500,
    currency: "USD",
    rating: 5.0,
    reviewCount: 98,
    itinerary: "Day 1: Arrival in Kigali. Day 2: Gorilla trekking. Day 3: Cultural tour and departure.",
    bookingUrl: "/booking/gorilla-trekking-experience",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Rwanda Gorilla Trekking Experience - 3 Days | Jae Travel Expeditions",
    metaDescription: "Get up close with mountain gorillas in Volcanoes National Park. 3-day gorilla trekking experience with expert guides and luxury accommodations.",
    keywords: ["Gorilla Trekking", "Rwanda", "Mountain Gorillas", "Volcanoes National Park"],
    url: "/tours/gorilla-trekking-experience",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "29",
    slug: "nyungwe-forest-canopy-walk",
    image: "/nyungwe-forests.jpg",
    title: "Nyungwe Forest Canopy Walk",
    description: "Walk among the treetops.",
    price: 450,
    currency: "USD",
    rating: 4.6,
    reviewCount: 51,
    itinerary: "Day 1: Arrival and forest orientation. Day 2: Canopy walk and chimpanzee tracking. Departure.",
    bookingUrl: "/booking/nyungwe-forest-canopy-walk",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Nyungwe Forest Canopy Walk - 2 Days | Jae Travel Expeditions",
    metaDescription: "Walk among the treetops in Nyungwe Forest, Rwanda. Experience the canopy walk and track chimpanzees in ancient rainforest.",
    keywords: ["Nyungwe Forest", "Canopy Walk", "Rwanda", "Chimpanzee Tracking"],
    url: "/tours/nyungwe-forest-canopy-walk",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "30",
    slug: "lake-kivu-relaxation",
    image: "/Lake-Kivu-Islands.jpg",
    title: "Lake Kivu Relaxation",
    description: "Relax by Africa's great lake.",
    price: 380,
    currency: "USD",
    rating: 4.4,
    reviewCount: 43,
    itinerary: "Day 1: Arrival and beach relaxation. Day 2: Boat tour and island visits. Day 3: Departure.",
    bookingUrl: "/booking/lake-kivu-relaxation",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Lake Kivu Relaxation - 3 Days | Jae Travel Expeditions",
    metaDescription: "Relax by Africa's great lake at Lake Kivu, Rwanda. Pristine beaches, island hopping, and stunning mountain views.",
    keywords: ["Lake Kivu", "Relaxation", "Rwanda", "Beach Holiday"],
    url: "/tours/lake-kivu-relaxation",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "31",
    slug: "akagera-national-park-safari",
    image: "/Akagera-national-park-1-750x450.jpg",
    title: "Akagera National Park",
    description: "Rwanda's only savanna park.",
    price: 520,
    currency: "USD",
    rating: 4.5,
    reviewCount: 48,
    itinerary: "Day 1: Arrival and afternoon game drive. Day 2: Full-day game drive and boat safari. Departure.",
    bookingUrl: "/booking/akagera-national-park-safari",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Akagera National Park Safari - 2 Days | Jae Travel Expeditions",
    metaDescription: "Explore Rwanda's only savanna park at Akagera National Park. Big Five safari with boat cruises on Lake Ihema.",
    keywords: ["Akagera", "National Park", "Rwanda Safari", "Big Five"],
    url: "/tours/akagera-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "32",
    slug: "kigali-city-tour",
    image: "/kigali-photo-600x300.jpg",
    title: "Kigali City Tour",
    description: "Explore the clean city of Kigali.",
    price: 150,
    currency: "USD",
    rating: 4.3,
    reviewCount: 67,
    itinerary: "Day 1: Full-day city tour including Genocide Memorial, markets, and cultural sites.",
    bookingUrl: "/booking/kigali-city-tour",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Kigali City Tour - 1 Day | Jae Travel Expeditions",
    metaDescription: "Explore the clean city of Kigali, Rwanda. Visit the Genocide Memorial, vibrant markets, and modern cultural centers.",
    keywords: ["Kigali", "City Tour", "Rwanda", "Genocide Memorial"],
    url: "/tours/kigali-city-tour",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "33",
    slug: "golden-monkey-tracking",
    image: "/golden-monkey-trekking.jpg",
    title: "Golden Monkey Tracking",
    description: "Track rare golden monkeys.",
    price: 680,
    currency: "USD",
    rating: 4.7,
    reviewCount: 39,
    itinerary: "Day 1: Arrival and briefing. Day 2: Golden monkey tracking and cultural visit. Departure.",
    bookingUrl: "/booking/golden-monkey-tracking",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Golden Monkey Tracking - 2 Days | Jae Travel Expeditions",
    metaDescription: "Track rare golden monkeys in Rwanda. Unique primate experience in Volcanoes National Park's bamboo forests.",
    keywords: ["Golden Monkey", "Tracking", "Rwanda", "Primate Trekking"],
    url: "/tours/golden-monkey-tracking",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "34",
    slug: "bwindi-gorilla-trekking",
    image: "/Magical-encounters-with-the-mountain-gorillas-of-Bwindi.jpg",
    title: "Bwindi Gorilla Trekking",
    description: "Trek mountain gorillas in Bwindi Impenetrable Forest, Uganda.",
    price: 2200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 87,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-3: Gorilla trekking. Day 4: Departure.",
    bookingUrl: "/booking/bwindi-gorilla-trekking",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Bwindi Gorilla Trekking - 4 Days | Jae Travel Expeditions",
    metaDescription: "Trek mountain gorillas in Bwindi Impenetrable Forest. 4-day Uganda gorilla trekking with expert guides and comfortable accommodations.",
    keywords: ["Bwindi", "Gorilla Trekking", "Uganda", "Mountain Gorillas"],
    url: "/tours/bwindi-gorilla-trekking",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "35",
    slug: "queen-elizabeth-national-park-safari",
    image: "/Queen-Elizabeth-National-Park.jpg",
    title: "Queen Elizabeth Safari",
    description: "Diverse wildlife in scenic landscapes at Queen Elizabeth National Park.",
    price: 1150,
    currency: "USD",
    rating: 4.6,
    reviewCount: 76,
    itinerary: "Day 1: Arrival. Day 2-4: Game drives and boat safari on Kazinga Channel. Day 5: Departure.",
    bookingUrl: "/booking/queen-elizabeth-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Queen Elizabeth Safari - 5 Days | Jae Travel Expeditions",
    metaDescription: "Experience diverse wildlife in scenic landscapes at Queen Elizabeth National Park. 5-day safari with game drives and boat cruises.",
    keywords: ["Queen Elizabeth", "National Park", "Uganda Safari", "Wildlife", "Kazinga Channel"],
    url: "/tours/queen-elizabeth-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "36",
    slug: "murchison-falls-national-park-safari",
    image: "/murchison-falls.webp",
    title: "Murchison Falls Adventure",
    description: "Witness the powerful Murchison Falls.",
    price: 980,
    currency: "USD",
    rating: 4.7,
    reviewCount: 64,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2-3: Game drives and boat safari to the falls. Day 4: Departure.",
    bookingUrl: "/booking/murchison-falls-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Murchison Falls Adventure - 4 Days | Jae Travel Expeditions",
    metaDescription: "Witness the powerful Murchison Falls in Uganda. Game drives, boat safaris, and spectacular waterfall views.",
    keywords: ["Murchison Falls", "Adventure", "Uganda", "Waterfall Safari"],
    url: "/tours/murchison-falls-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "37",
    slug: "kibale-national-park-chimpanzee-trekking",
    image: "/kibale-national-park-chimpanzees-uganda-590x390.jpg",
    title: "Kibale Chimpanzee Tracking",
    description: "Track our closest relatives.",
    price: 750,
    currency: "USD",
    rating: 4.5,
    reviewCount: 58,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Chimpanzee tracking. Day 3: Bigodi wetland walk and departure.",
    bookingUrl: "/booking/kibale-national-park-chimpanzee-trekking",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Kibale Chimpanzee Tracking - 3 Days | Jae Travel Expeditions",
    metaDescription: "Track our closest relatives in Kibale National Park, Uganda. Primate capital of the world with 13 primate species.",
    keywords: ["Kibale", "Chimpanzee Tracking", "Uganda", "Primate Safari"],
    url: "/tours/kibale-national-park-chimpanzee-trekking",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "38",
    slug: "lake-mburo-national-park-safari",
    image: "/lake-mburo-national-park.jpg",
    title: "Lake Mburo National Park",
    description: "Compact park with diverse wildlife.",
    price: 420,
    currency: "USD",
    rating: 4.3,
    reviewCount: 41,
    itinerary: "Day 1: Arrival and afternoon game drive. Day 2: Morning game drive and boat safari. Departure.",
    bookingUrl: "/booking/lake-mburo-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Lake Mburo National Park Safari - 2 Days | Jae Travel Expeditions",
    metaDescription: "Explore a compact park with diverse wildlife at Lake Mburo National Park, Uganda. Zebras, impalas, and boat safaris.",
    keywords: ["Lake Mburo", "National Park", "Uganda Safari", "Boat Safari"],
    url: "/tours/lake-mburo-national-park-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "39",
    slug: "rwenzori-mountains-hiking",
    image: "/Rwenzori-Mountains-03_1600p.jpg",
    title: "Rwenzori Mountains Hiking",
    description: "Hike the Mountains of the Moon.",
    price: 1800,
    currency: "USD",
    rating: 4.8,
    reviewCount: 35,
    itinerary: "Day 1: Arrival and briefing. Day 2-6: Hiking through various vegetation zones. Day 7: Descent and departure.",
    bookingUrl: "/booking/rwenzori-mountains-hiking",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Rwenzori Mountains Hiking - 7 Days | Jae Travel Expeditions",
    metaDescription: "Hike the Mountains of the Moon in Rwenzori Mountains, Uganda. Challenging trek through unique alpine vegetation.",
    keywords: ["Rwenzori", "Mountains", "Hiking", "Uganda", "Mountains of the Moon"],
    url: "/tours/rwenzori-mountains-hiking",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "40",
    slug: "jinja-adventure-tour",
    image: "/6-days-gorilla-tracking-and-rafting-jinja.jpg",
    title: "Jinja White Water Rafting",
    description: "Adventure at the source of the Nile.",
    price: 350,
    currency: "USD",
    rating: 4.6,
    reviewCount: 92,
    itinerary: "Day 1: Arrival and Nile source visit. Day 2: White water rafting and departure.",
    bookingUrl: "/booking/jinja-adventure-tour",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Jinja White Water Rafting - 2 Days | Jae Travel Expeditions",
    metaDescription: "Experience adventure at the source of the Nile in Jinja, Uganda. World-class white water rafting and adrenaline activities.",
    keywords: ["Jinja", "White Water Rafting", "Nile River", "Adventure", "Uganda"],
    url: "/tours/jinja-adventure-tour",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "41",
    slug: "lake-bunyonyi-relaxation-tour",
    image: "/lake_bunyonyi__uganda-the-pearl-of-africa.webp",
    title: "Lake Bunyonyi Relaxation",
    description: "Relax by Uganda's deepest lake.",
    price: 450,
    currency: "USD",
    rating: 4.4,
    reviewCount: 47,
    itinerary: "Day 1: Arrival and lake orientation. Day 2: Island hopping and canoeing. Day 3: Departure.",
    bookingUrl: "/booking/lake-bunyonyi-relaxation-tour",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Lake Bunyonyi Relaxation - 3 Days | Jae Travel Expeditions",
    metaDescription: "Relax by Uganda's deepest lake at Lake Bunyonyi. Scenic beauty, island hopping, and peaceful atmosphere.",
    keywords: ["Lake Bunyonyi", "Relaxation", "Uganda", "Island Hopping"],
    url: "/tours/lake-bunyonyi-relaxation-tour",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "42",
    slug: "ssese-islands-beach-holiday",
    image: "/Travel-to-Ssese-islands.jpg",
    title: "Ssese Islands Beach Holiday",
    description: "Beach paradise on Lake Victoria.",
    price: 650,
    currency: "USD",
    rating: 4.5,
    reviewCount: 53,
    itinerary: "Day 1: Arrival and beach relaxation. Day 2-3: Water sports and island exploration. Day 4: Departure.",
    bookingUrl: "/booking/ssese-islands-beach-holiday",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Ssese Islands Beach Holiday - 4 Days | Jae Travel Expeditions",
    metaDescription: "Experience beach paradise on Lake Victoria at Ssese Islands, Uganda. Tropical beaches, water sports, and relaxation.",
    keywords: ["Ssese Islands", "Beach Holiday", "Lake Victoria", "Uganda"],
    url: "/tours/ssese-islands-beach-holiday",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "43",
    slug: "lake-naivasha-boat-safari",
    image: "/Lake-Naivasha-National-Park-750x450.jpg",
    title: "Lake Naivasha Boat Safari",
    description: "Boat safari on freshwater Lake Naivasha with hippos, birds, and Crescent Island walking safari.",
    price: 150,
    currency: "USD",
    rating: 4.3,
    reviewCount: 61,
    itinerary: "Day 1: Boat safari on Lake Naivasha and walking safari on Crescent Island.",
    bookingUrl: "/booking/lake-naivasha-boat-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Lake Naivasha Boat Safari - 1 Day | Jae Travel Expeditions",
    metaDescription: "Enjoy a boat safari on freshwater Lake Naivasha with hippos, birds, and Crescent Island walking safari.",
    keywords: ["Lake Naivasha", "Boat Safari", "Kenya", "Crescent Island"],
    url: "/tours/lake-naivasha-boat-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "44",
    slug: "kenya-disability-safari",
    image: "/wheelchair-accessible-tanzania-safari.webp",
    title: "Accessible Kenya Safari Experience",
    description: "A fully accessible safari experience designed for travelers with mobility challenges, featuring wheelchair-accessible vehicles, accommodations, and tailored wildlife viewing.",
    price: 2450,
    currency: "USD",
    rating: 4.8,
    reviewCount: 42,
    itinerary: "7-day accessible safari experience in Kenya with adapted vehicles and accommodations",
    bookingUrl: "/booking/kenya-disability-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Accessible Kenya Safari Experience for People with Disabilities | Jae Travel Expeditions",
    metaDescription: "A fully accessible safari experience designed for travelers with mobility challenges in Kenya. Wheelchair-accessible vehicles and accommodations.",
    keywords: ["Accessible Safari Kenya", "Disability Travel Kenya", "Wheelchair Safari", "Accessible Wildlife Tours"],
    url: "/tours/kenya-disability-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "45",
    slug: "accessible-masai-mara-safari",
    image: "/Tineke-in-Kenya.png",
    title: "4-Day Accessible Masai Mara Experience",
    description: "A focused accessible safari in the Masai Mara with wheelchair-adapted vehicles, accessible tented camps, and front-row seats to the Great Migration.",
    price: 1450,
    currency: "USD",
    rating: 4.9,
    reviewCount: 38,
    itinerary: "4-day accessible safari in Masai Mara with adapted vehicles",
    bookingUrl: "/booking/accessible-masai-mara-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Accessible Masai Mara Safari for People with Disabilities | Jae Travel Expeditions",
    metaDescription: "A focused accessible safari in the Masai Mara with wheelchair-adapted vehicles and accessible tented camps.",
    keywords: ["Accessible Masai Mara", "Disability Safari Kenya", "Wheelchair Masai Mara"],
    url: "/tours/accessible-masai-mara-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "46",
    slug: "tanzania-accessible-safari",
    image: "/WhatsApp-Image-2025-01-15-at-12.06.45-PM.webp",
    title: "Tanzania Accessible Safari Adventure",
    description: "An inclusive journey through Tanzania's Serengeti and Ngorongoro Crater with adapted safari vehicles, accessible lodges, and unforgettable wildlife encounters.",
    price: 2950,
    currency: "USD",
    rating: 4.7,
    reviewCount: 29,
    itinerary: "8-day accessible safari in Tanzania",
    bookingUrl: "/booking/tanzania-accessible-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Tanzania Accessible Safari Adventure | Jae Travel Expeditions",
    metaDescription: "An inclusive journey through Tanzania's Serengeti and Ngorongoro Crater with adapted safari vehicles and accessible lodges.",
    keywords: ["Accessible Tanzania Safari", "Disability Travel Tanzania", "Wheelchair Safari Tanzania"],
    url: "/tours/tanzania-accessible-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    id: "49",
    slug: "east-africa-grand-accessible-safari",
    image: "/ngorongoro-header-3.jpg",
    title: "East Africa Grand Accessible Safari",
    description: "The ultimate East African accessible safari across Kenya and Tanzania, combining Maasai Mara, Serengeti, and Ngorongoro with premium accessible accommodations.",
    price: 5800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 18,
    itinerary: "12-day grand accessible safari across Kenya and Tanzania",
    bookingUrl: "/booking/east-africa-grand-accessible-safari",
    region: "East Africa",
    country: "Multi-Country",
    metaTitle: "East Africa Grand Accessible Safari | Jae Travel Expeditions",
    metaDescription: "The ultimate East African accessible safari across Kenya and Tanzania with premium accessible accommodations.",
    keywords: [
      "East Africa Accessible Safari",
      "Multi-Country Safari",
      "Disability Travel East Africa",
      "Grand Safari",
    ],
    url: "/tours/east-africa-grand-accessible-safari",
    duration: undefined,
    highlights: undefined,
    included: undefined,
    excluded: undefined,
    difficulty: undefined,
    groupSize: undefined,
    category: undefined,
    shortDescription: ""
  },
  {
    "id": "50",
    "slug": "carnivore-experience",
    "image": "/carnivore-dining.jpg",
    "title": "Carnivore Experience",
    "description": "Indulge in a unique dining adventure at the famous Carnivore Restaurant in Nairobi, featuring exotic game meats and vibrant Kenyan hospitality.",
    "price": 150,
    "currency": "USD",
    "rating": 4.7,
    "reviewCount": 25,
    "itinerary": "Half-day dining experience in Nairobi",
    "bookingUrl": "/booking/carnivore-experience",
    "region": "East Africa",
    "country": "Kenya",
    "metaTitle": "Carnivore Experience | Jae Travel Expeditions",
    "metaDescription": "Enjoy a unique dining adventure at Nairobi's Carnivore Restaurant with exotic game meats and Kenyan hospitality.",
    "keywords": [
      "Carnivore Restaurant",
      "Nairobi Dining",
      "Kenya Food Tour",
      "Game Meat Experience"
    ],
    "url": "/tour/carnivore-experience",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "51",
    "slug": "safari-madoa-doa",
    "image": "/madoa-doa-safari.jpg",
    "title": "Safari Madoa Doa",
    "description": "Embark on an exclusive safari adventure through Kenya’s premier wildlife reserves, spotting the Big Five in their natural habitat.",
    "price": 3200,
    "currency": "USD",
    "rating": 4.8,
    "reviewCount": 15,
    "itinerary": "7-day safari across Kenyan reserves",
    "bookingUrl": "/booking/safari-madoa-doa",
    "region": "East Africa",
    "country": "Kenya",
    "metaTitle": "Safari Madoa Doa | Jae Travel Expeditions",
    "metaDescription": "Experience a 7-day exclusive safari in Kenya, spotting the Big Five in premier wildlife reserves.",
    "keywords": [
      "Kenya Safari",
      "Big Five Safari",
      "Wildlife Adventure",
      "Madoa Doa Safari"
    ],
    "url": "/tour/safari-madoa-doa",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "52",
    "slug": "best-of-zanzibar",
    "image": "/zanzibar-beach.jpg",
    "title": "Best of Zanzibar",
    "description": "Discover the tropical paradise of Zanzibar with its pristine beaches, historic Stone Town, and vibrant spice tours.",
    "price": 2500,
    "currency": "USD",
    "rating": 4.9,
    "reviewCount": 22,
    "itinerary": "8-day cultural and beach tour in Zanzibar",
    "bookingUrl": "/booking/best-of-zanzibar",
    "region": "East Africa",
    "country": "Tanzania",
    "metaTitle": "Best of Zanzibar | Jae Travel Expeditions",
    "metaDescription": "Explore Zanzibar’s beaches, Stone Town, and spice tours on an 8-day cultural and beach adventure.",
    "keywords": [
      "Zanzibar Tour",
      "Stone Town",
      "Spice Tour",
      "Tanzania Beach Holiday"
    ],
    "url": "/tour/best-of-zanzibar",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "53",
    "slug": "classic-sky-safari-2",
    "image": "/sky-safari.jpg",
    "title": "Classic Sky Safari 2",
    "description": "Soar above East Africa’s iconic landscapes on a luxury sky safari, visiting Amboseli, Meru, and the Maasai Mara.",
    "price": 6500,
    "currency": "USD",
    "rating": 5.0,
    "reviewCount": 12,
    "itinerary": "10-day luxury air safari across Kenya",
    "bookingUrl": "/booking/classic-sky-safari-2",
    "region": "East Africa",
    "country": "Kenya",
    "metaTitle": "Classic Sky Safari 2 | Jae Travel Expeditions",
    "metaDescription": "Experience a 10-day luxury sky safari over Kenya’s Amboseli, Meru, and Maasai Mara.",
    "keywords": [
      "Sky Safari",
      "Luxury Safari Kenya",
      "Maasai Mara",
      "Amboseli Tour"
    ],
    "url": "/tour/classic-sky-safari-2",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "54",
    "slug": "nairobi-national-park-tour",
    "image": "/nairobi-park.jpg",
    "title": "Nairobi National Park Tour",
    "description": "Explore Nairobi National Park, a unique wildlife haven near the city, home to rhinos, lions, and stunning savanna views.",
    "price": 200,
    "currency": "USD",
    "rating": 4.6,
    "reviewCount": 30,
    "itinerary": "Half-day wildlife tour in Nairobi",
    "bookingUrl": "/booking/nairobi-national-park-tour",
    "region": "East Africa",
    "country": "Kenya",
    "metaTitle": "Nairobi National Park Tour | Jae Travel Expeditions",
    "metaDescription": "Discover wildlife near Nairobi with a half-day tour of Nairobi National Park, home to rhinos and lions.",
    "keywords": [
      "Nairobi National Park",
      "Kenya Wildlife Tour",
      "Day Safari Nairobi",
      "Rhino Safari"
    ],
    "url": "/tour/nairobi-national-park-tour",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "55",
    "slug": "visit-a-thousand-hills-distilleries",
    "image": "/thousand-hills-distillery.jpg",
    "title": "Visit a Thousand Hills Distilleries",
    "description": "Experience Rwanda’s artisanal spirit scene with a tour of Thousand Hills Distilleries, tasting premium local beverages.",
    "price": 100,
    "currency": "USD",
    "rating": 4.5,
    "reviewCount": 10,
    "itinerary": "Half-day distillery tour in Rwanda",
    "bookingUrl": "/booking/visit-a-thousand-hills-distilleries",
    "region": "East Africa",
    "country": "Rwanda",
    "metaTitle": "Visit a Thousand Hills Distilleries | Jae Travel Expeditions",
    "metaDescription": "Tour Rwanda’s Thousand Hills Distilleries and taste premium local spirits on a half-day experience.",
    "keywords": [
      "Rwanda Distillery Tour",
      "Thousand Hills Distillery",
      "Local Spirits Rwanda",
      "Cultural Tour Rwanda"
    ],
    "url": "/tour/visit-a-thousand-hills-distilleries",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "56",
    "slug": "this-is-africa-nyamirambo-womens-center",
    "image": "/nyamirambo-center.jpg",
    "title": "This is Africa Nyamirambo Women’s Center",
    "description": "Immerse yourself in Rwandan culture with a visit to Nyamirambo Women’s Center, exploring local crafts and community initiatives.",
    "price": 80,
    "currency": "USD",
    "rating": 4.8,
    "reviewCount": 15,
    "itinerary": "Half-day cultural tour in Kigali",
    "bookingUrl": "/booking/this-is-africa-nyamirambo-womens-center",
    "region": "East Africa",
    "country": "Rwanda",
    "metaTitle": "Nyamirambo Women’s Center Tour | Jae Travel Expeditions",
    "metaDescription": "Explore Rwandan culture and crafts at Nyamirambo Women’s Center in Kigali on a half-day tour.",
    "keywords": [
      "Nyamirambo Women’s Center",
      "Rwanda Cultural Tour",
      "Kigali Community Tour",
      "African Crafts"
    ],
    "url": "/tour/this-is-africa-nyamirambo-womens-center",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "57",
    "slug": "relaxation-at-the-beach",
    "image": "/beach-relaxation.jpg",
    "title": "Relaxation at the Beach",
    "description": "Unwind on the pristine beaches of East Africa, enjoying sun, sand, and sea in a serene coastal escape.",
    "price": 1200,
    "currency": "USD",
    "rating": 4.7,
    "reviewCount": 20,
    "itinerary": "5-day beach retreat in East Africa",
    "bookingUrl": "/booking/relaxation-at-the-beach",
    "region": "East Africa",
    "country": "Tanzania",
    "metaTitle": "Relaxation at the Beach | Jae Travel Expeditions",
    "metaDescription": "Unwind on East Africa’s pristine beaches with a 5-day coastal retreat.",
    "keywords": [
      "Beach Holiday East Africa",
      "Coastal Retreat",
      "Tanzania Beach Tour",
      "Relaxation Tour"
    ],
    "url": "/tour/relaxation-at-the-beach",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
  {
    "id": "58",
    "slug": "safari-dwika",
    "image": "/dwika-safari.jpg",
    "title": "Safari Dwika",
    "description": "Join an adventurous safari through Tanzania’s iconic parks, witnessing diverse wildlife and stunning landscapes.",
    "price": 3500,
    "currency": "USD",
    "rating": 4.8,
    "reviewCount": 18,
    "itinerary": "7-day safari in Tanzania",
    "bookingUrl": "/booking/safari-dwika",
    "region": "East Africa",
    "country": "Tanzania",
    "metaTitle": "Safari Dwika | Jae Travel Expeditions",
    "metaDescription": "Experience a 7-day safari adventure through Tanzania’s iconic wildlife parks.",
    "keywords": [
      "Tanzania Safari",
      "Wildlife Tour",
      "Dwika Safari",
      "East Africa Adventure"
    ],
    "url": "/tour/safari-dwika",
    "duration": undefined,
    "highlights": undefined,
    "included": undefined,
    "excluded": undefined,
    "difficulty": undefined,
    "groupSize": undefined,
    "category": undefined,
    shortDescription: ""
  },
]

export const disabilityTours = tours.filter(
  (tour) => tour.slug.includes("accessible") || tour.slug.includes("disability"),
)

export const toursByCountry = {
  Kenya: tours.filter((t) => t.country === "Kenya"),
  Tanzania: tours.filter((t) => t.country === "Tanzania"),
  Rwanda: tours.filter((t) => t.country === "Rwanda"),
  Uganda: tours.filter((t) => t.country === "Uganda"),
  "Multi-Country": tours.filter((t) => t.country === "Multi-Country"),
}

export const toursOnOffer = tours.filter((tour) => tour.isOnOffer)
